package com.deodio.elearning.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AccountExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public AccountExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAccountDomainIsNull() {
			addCriterion("account_domain is null");
			return (Criteria) this;
		}

		public Criteria andAccountDomainIsNotNull() {
			addCriterion("account_domain is not null");
			return (Criteria) this;
		}

		public Criteria andAccountDomainEqualTo(String value) {
			addCriterion("account_domain =", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainNotEqualTo(String value) {
			addCriterion("account_domain <>", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainGreaterThan(String value) {
			addCriterion("account_domain >", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainGreaterThanOrEqualTo(String value) {
			addCriterion("account_domain >=", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainLessThan(String value) {
			addCriterion("account_domain <", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainLessThanOrEqualTo(String value) {
			addCriterion("account_domain <=", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainLike(String value) {
			addCriterion("account_domain like", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainNotLike(String value) {
			addCriterion("account_domain not like", value, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainIn(List<String> values) {
			addCriterion("account_domain in", values, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainNotIn(List<String> values) {
			addCriterion("account_domain not in", values, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainBetween(String value1, String value2) {
			addCriterion("account_domain between", value1, value2, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountDomainNotBetween(String value1, String value2) {
			addCriterion("account_domain not between", value1, value2, "accountDomain");
			return (Criteria) this;
		}

		public Criteria andAccountStatusIsNull() {
			addCriterion("account_status is null");
			return (Criteria) this;
		}

		public Criteria andAccountStatusIsNotNull() {
			addCriterion("account_status is not null");
			return (Criteria) this;
		}

		public Criteria andAccountStatusEqualTo(Integer value) {
			addCriterion("account_status =", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusNotEqualTo(Integer value) {
			addCriterion("account_status <>", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusGreaterThan(Integer value) {
			addCriterion("account_status >", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_status >=", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusLessThan(Integer value) {
			addCriterion("account_status <", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusLessThanOrEqualTo(Integer value) {
			addCriterion("account_status <=", value, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusIn(List<Integer> values) {
			addCriterion("account_status in", values, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusNotIn(List<Integer> values) {
			addCriterion("account_status not in", values, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusBetween(Integer value1, Integer value2) {
			addCriterion("account_status between", value1, value2, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("account_status not between", value1, value2, "accountStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusIsNull() {
			addCriterion("account_paypal_status is null");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusIsNotNull() {
			addCriterion("account_paypal_status is not null");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusEqualTo(Integer value) {
			addCriterion("account_paypal_status =", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusNotEqualTo(Integer value) {
			addCriterion("account_paypal_status <>", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusGreaterThan(Integer value) {
			addCriterion("account_paypal_status >", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("account_paypal_status >=", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusLessThan(Integer value) {
			addCriterion("account_paypal_status <", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusLessThanOrEqualTo(Integer value) {
			addCriterion("account_paypal_status <=", value, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusIn(List<Integer> values) {
			addCriterion("account_paypal_status in", values, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusNotIn(List<Integer> values) {
			addCriterion("account_paypal_status not in", values, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusBetween(Integer value1, Integer value2) {
			addCriterion("account_paypal_status between", value1, value2, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("account_paypal_status not between", value1, value2, "accountPaypalStatus");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateIsNull() {
			addCriterion("account_paypal_date is null");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateIsNotNull() {
			addCriterion("account_paypal_date is not null");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateEqualTo(Date value) {
			addCriterionForJDBCDate("account_paypal_date =", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("account_paypal_date <>", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateGreaterThan(Date value) {
			addCriterionForJDBCDate("account_paypal_date >", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("account_paypal_date >=", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateLessThan(Date value) {
			addCriterionForJDBCDate("account_paypal_date <", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("account_paypal_date <=", value, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateIn(List<Date> values) {
			addCriterionForJDBCDate("account_paypal_date in", values, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("account_paypal_date not in", values, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("account_paypal_date between", value1, value2, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andAccountPaypalDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("account_paypal_date not between", value1, value2, "accountPaypalDate");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNull() {
			addCriterion("create_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNotNull() {
			addCriterion("create_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateIdEqualTo(String value) {
			addCriterion("create_id =", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotEqualTo(String value) {
			addCriterion("create_id <>", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThan(String value) {
			addCriterion("create_id >", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
			addCriterion("create_id >=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThan(String value) {
			addCriterion("create_id <", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThanOrEqualTo(String value) {
			addCriterion("create_id <=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLike(String value) {
			addCriterion("create_id like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotLike(String value) {
			addCriterion("create_id not like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdIn(List<String> values) {
			addCriterion("create_id in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotIn(List<String> values) {
			addCriterion("create_id not in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdBetween(String value1, String value2) {
			addCriterion("create_id between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotBetween(String value1, String value2) {
			addCriterion("create_id not between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("update_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("update_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("update_id =", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("update_id <>", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("update_id >", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("update_id >=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("update_id <", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("update_id <=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("update_id like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("update_id not like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIn(List<String> values) {
			addCriterion("update_id in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotIn(List<String> values) {
			addCriterion("update_id not in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("update_id between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("update_id not between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterionForJDBCDate("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCDate("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCDate("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCDate("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlIsNull() {
			addCriterion("logo_link_url is null");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlIsNotNull() {
			addCriterion("logo_link_url is not null");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlEqualTo(String value) {
			addCriterion("logo_link_url =", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlNotEqualTo(String value) {
			addCriterion("logo_link_url <>", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlGreaterThan(String value) {
			addCriterion("logo_link_url >", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("logo_link_url >=", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlLessThan(String value) {
			addCriterion("logo_link_url <", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlLessThanOrEqualTo(String value) {
			addCriterion("logo_link_url <=", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlLike(String value) {
			addCriterion("logo_link_url like", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlNotLike(String value) {
			addCriterion("logo_link_url not like", value, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlIn(List<String> values) {
			addCriterion("logo_link_url in", values, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlNotIn(List<String> values) {
			addCriterion("logo_link_url not in", values, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlBetween(String value1, String value2) {
			addCriterion("logo_link_url between", value1, value2, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andLogoLinkUrlNotBetween(String value1, String value2) {
			addCriterion("logo_link_url not between", value1, value2, "logoLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlIsNull() {
			addCriterion("header_link_url is null");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlIsNotNull() {
			addCriterion("header_link_url is not null");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlEqualTo(String value) {
			addCriterion("header_link_url =", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlNotEqualTo(String value) {
			addCriterion("header_link_url <>", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlGreaterThan(String value) {
			addCriterion("header_link_url >", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("header_link_url >=", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlLessThan(String value) {
			addCriterion("header_link_url <", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlLessThanOrEqualTo(String value) {
			addCriterion("header_link_url <=", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlLike(String value) {
			addCriterion("header_link_url like", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlNotLike(String value) {
			addCriterion("header_link_url not like", value, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlIn(List<String> values) {
			addCriterion("header_link_url in", values, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlNotIn(List<String> values) {
			addCriterion("header_link_url not in", values, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlBetween(String value1, String value2) {
			addCriterion("header_link_url between", value1, value2, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andHeaderLinkUrlNotBetween(String value1, String value2) {
			addCriterion("header_link_url not between", value1, value2, "headerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlIsNull() {
			addCriterion("banner_link_url is null");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlIsNotNull() {
			addCriterion("banner_link_url is not null");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlEqualTo(String value) {
			addCriterion("banner_link_url =", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlNotEqualTo(String value) {
			addCriterion("banner_link_url <>", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlGreaterThan(String value) {
			addCriterion("banner_link_url >", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("banner_link_url >=", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlLessThan(String value) {
			addCriterion("banner_link_url <", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlLessThanOrEqualTo(String value) {
			addCriterion("banner_link_url <=", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlLike(String value) {
			addCriterion("banner_link_url like", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlNotLike(String value) {
			addCriterion("banner_link_url not like", value, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlIn(List<String> values) {
			addCriterion("banner_link_url in", values, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlNotIn(List<String> values) {
			addCriterion("banner_link_url not in", values, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlBetween(String value1, String value2) {
			addCriterion("banner_link_url between", value1, value2, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andBannerLinkUrlNotBetween(String value1, String value2) {
			addCriterion("banner_link_url not between", value1, value2, "bannerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlIsNull() {
			addCriterion("footer_link_url is null");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlIsNotNull() {
			addCriterion("footer_link_url is not null");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlEqualTo(String value) {
			addCriterion("footer_link_url =", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlNotEqualTo(String value) {
			addCriterion("footer_link_url <>", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlGreaterThan(String value) {
			addCriterion("footer_link_url >", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("footer_link_url >=", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlLessThan(String value) {
			addCriterion("footer_link_url <", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlLessThanOrEqualTo(String value) {
			addCriterion("footer_link_url <=", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlLike(String value) {
			addCriterion("footer_link_url like", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlNotLike(String value) {
			addCriterion("footer_link_url not like", value, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlIn(List<String> values) {
			addCriterion("footer_link_url in", values, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlNotIn(List<String> values) {
			addCriterion("footer_link_url not in", values, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlBetween(String value1, String value2) {
			addCriterion("footer_link_url between", value1, value2, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andFooterLinkUrlNotBetween(String value1, String value2) {
			addCriterion("footer_link_url not between", value1, value2, "footerLinkUrl");
			return (Criteria) this;
		}

		public Criteria andThemeIsNull() {
			addCriterion("theme is null");
			return (Criteria) this;
		}

		public Criteria andThemeIsNotNull() {
			addCriterion("theme is not null");
			return (Criteria) this;
		}

		public Criteria andThemeEqualTo(Integer value) {
			addCriterion("theme =", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotEqualTo(Integer value) {
			addCriterion("theme <>", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThan(Integer value) {
			addCriterion("theme >", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeGreaterThanOrEqualTo(Integer value) {
			addCriterion("theme >=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThan(Integer value) {
			addCriterion("theme <", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeLessThanOrEqualTo(Integer value) {
			addCriterion("theme <=", value, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeIn(List<Integer> values) {
			addCriterion("theme in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotIn(List<Integer> values) {
			addCriterion("theme not in", values, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeBetween(Integer value1, Integer value2) {
			addCriterion("theme between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andThemeNotBetween(Integer value1, Integer value2) {
			addCriterion("theme not between", value1, value2, "theme");
			return (Criteria) this;
		}

		public Criteria andLayoutIsNull() {
			addCriterion("layout is null");
			return (Criteria) this;
		}

		public Criteria andLayoutIsNotNull() {
			addCriterion("layout is not null");
			return (Criteria) this;
		}

		public Criteria andLayoutEqualTo(Integer value) {
			addCriterion("layout =", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotEqualTo(Integer value) {
			addCriterion("layout <>", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutGreaterThan(Integer value) {
			addCriterion("layout >", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutGreaterThanOrEqualTo(Integer value) {
			addCriterion("layout >=", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutLessThan(Integer value) {
			addCriterion("layout <", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutLessThanOrEqualTo(Integer value) {
			addCriterion("layout <=", value, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutIn(List<Integer> values) {
			addCriterion("layout in", values, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotIn(List<Integer> values) {
			addCriterion("layout not in", values, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutBetween(Integer value1, Integer value2) {
			addCriterion("layout between", value1, value2, "layout");
			return (Criteria) this;
		}

		public Criteria andLayoutNotBetween(Integer value1, Integer value2) {
			addCriterion("layout not between", value1, value2, "layout");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixIsNull() {
			addCriterion("capability_prefix is null");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixIsNotNull() {
			addCriterion("capability_prefix is not null");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixEqualTo(String value) {
			addCriterion("capability_prefix =", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixNotEqualTo(String value) {
			addCriterion("capability_prefix <>", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixGreaterThan(String value) {
			addCriterion("capability_prefix >", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixGreaterThanOrEqualTo(String value) {
			addCriterion("capability_prefix >=", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixLessThan(String value) {
			addCriterion("capability_prefix <", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixLessThanOrEqualTo(String value) {
			addCriterion("capability_prefix <=", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixLike(String value) {
			addCriterion("capability_prefix like", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixNotLike(String value) {
			addCriterion("capability_prefix not like", value, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixIn(List<String> values) {
			addCriterion("capability_prefix in", values, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixNotIn(List<String> values) {
			addCriterion("capability_prefix not in", values, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixBetween(String value1, String value2) {
			addCriterion("capability_prefix between", value1, value2, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityPrefixNotBetween(String value1, String value2) {
			addCriterion("capability_prefix not between", value1, value2, "capabilityPrefix");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelIsNull() {
			addCriterion("capability_level is null");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelIsNotNull() {
			addCriterion("capability_level is not null");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelEqualTo(Integer value) {
			addCriterion("capability_level =", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelNotEqualTo(Integer value) {
			addCriterion("capability_level <>", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelGreaterThan(Integer value) {
			addCriterion("capability_level >", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("capability_level >=", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelLessThan(Integer value) {
			addCriterion("capability_level <", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelLessThanOrEqualTo(Integer value) {
			addCriterion("capability_level <=", value, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelIn(List<Integer> values) {
			addCriterion("capability_level in", values, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelNotIn(List<Integer> values) {
			addCriterion("capability_level not in", values, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelBetween(Integer value1, Integer value2) {
			addCriterion("capability_level between", value1, value2, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("capability_level not between", value1, value2, "capabilityLevel");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionIsNull() {
			addCriterion("capability_level_distribution is null");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionIsNotNull() {
			addCriterion("capability_level_distribution is not null");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionEqualTo(Short value) {
			addCriterion("capability_level_distribution =", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionNotEqualTo(Short value) {
			addCriterion("capability_level_distribution <>", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionGreaterThan(Short value) {
			addCriterion("capability_level_distribution >", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionGreaterThanOrEqualTo(Short value) {
			addCriterion("capability_level_distribution >=", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionLessThan(Short value) {
			addCriterion("capability_level_distribution <", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionLessThanOrEqualTo(Short value) {
			addCriterion("capability_level_distribution <=", value, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionIn(List<Short> values) {
			addCriterion("capability_level_distribution in", values, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionNotIn(List<Short> values) {
			addCriterion("capability_level_distribution not in", values, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionBetween(Short value1, Short value2) {
			addCriterion("capability_level_distribution between", value1, value2, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityLevelDistributionNotBetween(Short value1, Short value2) {
			addCriterion("capability_level_distribution not between", value1, value2, "capabilityLevelDistribution");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreIsNull() {
			addCriterion("capability_cal_score is null");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreIsNotNull() {
			addCriterion("capability_cal_score is not null");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreEqualTo(Short value) {
			addCriterion("capability_cal_score =", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreNotEqualTo(Short value) {
			addCriterion("capability_cal_score <>", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreGreaterThan(Short value) {
			addCriterion("capability_cal_score >", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreGreaterThanOrEqualTo(Short value) {
			addCriterion("capability_cal_score >=", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreLessThan(Short value) {
			addCriterion("capability_cal_score <", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreLessThanOrEqualTo(Short value) {
			addCriterion("capability_cal_score <=", value, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreIn(List<Short> values) {
			addCriterion("capability_cal_score in", values, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreNotIn(List<Short> values) {
			addCriterion("capability_cal_score not in", values, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreBetween(Short value1, Short value2) {
			addCriterion("capability_cal_score between", value1, value2, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCalScoreNotBetween(Short value1, Short value2) {
			addCriterion("capability_cal_score not between", value1, value2, "capabilityCalScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreIsNull() {
			addCriterion("capability_customize_score is null");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreIsNotNull() {
			addCriterion("capability_customize_score is not null");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreEqualTo(Integer value) {
			addCriterion("capability_customize_score =", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreNotEqualTo(Integer value) {
			addCriterion("capability_customize_score <>", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreGreaterThan(Integer value) {
			addCriterion("capability_customize_score >", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("capability_customize_score >=", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreLessThan(Integer value) {
			addCriterion("capability_customize_score <", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreLessThanOrEqualTo(Integer value) {
			addCriterion("capability_customize_score <=", value, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreIn(List<Integer> values) {
			addCriterion("capability_customize_score in", values, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreNotIn(List<Integer> values) {
			addCriterion("capability_customize_score not in", values, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreBetween(Integer value1, Integer value2) {
			addCriterion("capability_customize_score between", value1, value2, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andCapabilityCustomizeScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("capability_customize_score not between", value1, value2, "capabilityCustomizeScore");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNull() {
			addCriterion("owner_id is null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIsNotNull() {
			addCriterion("owner_id is not null");
			return (Criteria) this;
		}

		public Criteria andOwnerIdEqualTo(String value) {
			addCriterion("owner_id =", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotEqualTo(String value) {
			addCriterion("owner_id <>", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThan(String value) {
			addCriterion("owner_id >", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdGreaterThanOrEqualTo(String value) {
			addCriterion("owner_id >=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThan(String value) {
			addCriterion("owner_id <", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLessThanOrEqualTo(String value) {
			addCriterion("owner_id <=", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdLike(String value) {
			addCriterion("owner_id like", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotLike(String value) {
			addCriterion("owner_id not like", value, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdIn(List<String> values) {
			addCriterion("owner_id in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotIn(List<String> values) {
			addCriterion("owner_id not in", values, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdBetween(String value1, String value2) {
			addCriterion("owner_id between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andOwnerIdNotBetween(String value1, String value2) {
			addCriterion("owner_id not between", value1, value2, "ownerId");
			return (Criteria) this;
		}

		public Criteria andIsValidIsNull() {
			addCriterion("is_valid is null");
			return (Criteria) this;
		}

		public Criteria andIsValidIsNotNull() {
			addCriterion("is_valid is not null");
			return (Criteria) this;
		}

		public Criteria andIsValidEqualTo(Short value) {
			addCriterion("is_valid =", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidNotEqualTo(Short value) {
			addCriterion("is_valid <>", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidGreaterThan(Short value) {
			addCriterion("is_valid >", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidGreaterThanOrEqualTo(Short value) {
			addCriterion("is_valid >=", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidLessThan(Short value) {
			addCriterion("is_valid <", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidLessThanOrEqualTo(Short value) {
			addCriterion("is_valid <=", value, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidIn(List<Short> values) {
			addCriterion("is_valid in", values, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidNotIn(List<Short> values) {
			addCriterion("is_valid not in", values, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidBetween(Short value1, Short value2) {
			addCriterion("is_valid between", value1, value2, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsValidNotBetween(Short value1, Short value2) {
			addCriterion("is_valid not between", value1, value2, "isValid");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckIsNull() {
			addCriterion("is_need_check is null");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckIsNotNull() {
			addCriterion("is_need_check is not null");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckEqualTo(Short value) {
			addCriterion("is_need_check =", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckNotEqualTo(Short value) {
			addCriterion("is_need_check <>", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckGreaterThan(Short value) {
			addCriterion("is_need_check >", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckGreaterThanOrEqualTo(Short value) {
			addCriterion("is_need_check >=", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckLessThan(Short value) {
			addCriterion("is_need_check <", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckLessThanOrEqualTo(Short value) {
			addCriterion("is_need_check <=", value, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckIn(List<Short> values) {
			addCriterion("is_need_check in", values, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckNotIn(List<Short> values) {
			addCriterion("is_need_check not in", values, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckBetween(Short value1, Short value2) {
			addCriterion("is_need_check between", value1, value2, "isNeedCheck");
			return (Criteria) this;
		}

		public Criteria andIsNeedCheckNotBetween(Short value1, Short value2) {
			addCriterion("is_need_check not between", value1, value2, "isNeedCheck");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_account
	 * @mbggenerated  Mon May 21 14:19:52 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_account
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 28 14:43:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}