package com.deodio.elearning.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AttachmentMediaItemExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public AttachmentMediaItemExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andMediaIdIsNull() {
			addCriterion("media_id is null");
			return (Criteria) this;
		}

		public Criteria andMediaIdIsNotNull() {
			addCriterion("media_id is not null");
			return (Criteria) this;
		}

		public Criteria andMediaIdEqualTo(String value) {
			addCriterion("media_id =", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotEqualTo(String value) {
			addCriterion("media_id <>", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdGreaterThan(String value) {
			addCriterion("media_id >", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdGreaterThanOrEqualTo(String value) {
			addCriterion("media_id >=", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdLessThan(String value) {
			addCriterion("media_id <", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdLessThanOrEqualTo(String value) {
			addCriterion("media_id <=", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdLike(String value) {
			addCriterion("media_id like", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotLike(String value) {
			addCriterion("media_id not like", value, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdIn(List<String> values) {
			addCriterion("media_id in", values, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotIn(List<String> values) {
			addCriterion("media_id not in", values, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdBetween(String value1, String value2) {
			addCriterion("media_id between", value1, value2, "mediaId");
			return (Criteria) this;
		}

		public Criteria andMediaIdNotBetween(String value1, String value2) {
			addCriterion("media_id not between", value1, value2, "mediaId");
			return (Criteria) this;
		}

		public Criteria andItemNameIsNull() {
			addCriterion("item_name is null");
			return (Criteria) this;
		}

		public Criteria andItemNameIsNotNull() {
			addCriterion("item_name is not null");
			return (Criteria) this;
		}

		public Criteria andItemNameEqualTo(String value) {
			addCriterion("item_name =", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotEqualTo(String value) {
			addCriterion("item_name <>", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameGreaterThan(String value) {
			addCriterion("item_name >", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameGreaterThanOrEqualTo(String value) {
			addCriterion("item_name >=", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLessThan(String value) {
			addCriterion("item_name <", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLessThanOrEqualTo(String value) {
			addCriterion("item_name <=", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameLike(String value) {
			addCriterion("item_name like", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotLike(String value) {
			addCriterion("item_name not like", value, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameIn(List<String> values) {
			addCriterion("item_name in", values, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotIn(List<String> values) {
			addCriterion("item_name not in", values, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameBetween(String value1, String value2) {
			addCriterion("item_name between", value1, value2, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemNameNotBetween(String value1, String value2) {
			addCriterion("item_name not between", value1, value2, "itemName");
			return (Criteria) this;
		}

		public Criteria andItemSizeIsNull() {
			addCriterion("item_size is null");
			return (Criteria) this;
		}

		public Criteria andItemSizeIsNotNull() {
			addCriterion("item_size is not null");
			return (Criteria) this;
		}

		public Criteria andItemSizeEqualTo(Long value) {
			addCriterion("item_size =", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeNotEqualTo(Long value) {
			addCriterion("item_size <>", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeGreaterThan(Long value) {
			addCriterion("item_size >", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeGreaterThanOrEqualTo(Long value) {
			addCriterion("item_size >=", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeLessThan(Long value) {
			addCriterion("item_size <", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeLessThanOrEqualTo(Long value) {
			addCriterion("item_size <=", value, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeIn(List<Long> values) {
			addCriterion("item_size in", values, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeNotIn(List<Long> values) {
			addCriterion("item_size not in", values, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeBetween(Long value1, Long value2) {
			addCriterion("item_size between", value1, value2, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemSizeNotBetween(Long value1, Long value2) {
			addCriterion("item_size not between", value1, value2, "itemSize");
			return (Criteria) this;
		}

		public Criteria andItemExtIsNull() {
			addCriterion("item_ext is null");
			return (Criteria) this;
		}

		public Criteria andItemExtIsNotNull() {
			addCriterion("item_ext is not null");
			return (Criteria) this;
		}

		public Criteria andItemExtEqualTo(String value) {
			addCriterion("item_ext =", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtNotEqualTo(String value) {
			addCriterion("item_ext <>", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtGreaterThan(String value) {
			addCriterion("item_ext >", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtGreaterThanOrEqualTo(String value) {
			addCriterion("item_ext >=", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtLessThan(String value) {
			addCriterion("item_ext <", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtLessThanOrEqualTo(String value) {
			addCriterion("item_ext <=", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtLike(String value) {
			addCriterion("item_ext like", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtNotLike(String value) {
			addCriterion("item_ext not like", value, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtIn(List<String> values) {
			addCriterion("item_ext in", values, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtNotIn(List<String> values) {
			addCriterion("item_ext not in", values, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtBetween(String value1, String value2) {
			addCriterion("item_ext between", value1, value2, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemExtNotBetween(String value1, String value2) {
			addCriterion("item_ext not between", value1, value2, "itemExt");
			return (Criteria) this;
		}

		public Criteria andItemUrlIsNull() {
			addCriterion("item_url is null");
			return (Criteria) this;
		}

		public Criteria andItemUrlIsNotNull() {
			addCriterion("item_url is not null");
			return (Criteria) this;
		}

		public Criteria andItemUrlEqualTo(String value) {
			addCriterion("item_url =", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlNotEqualTo(String value) {
			addCriterion("item_url <>", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlGreaterThan(String value) {
			addCriterion("item_url >", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlGreaterThanOrEqualTo(String value) {
			addCriterion("item_url >=", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlLessThan(String value) {
			addCriterion("item_url <", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlLessThanOrEqualTo(String value) {
			addCriterion("item_url <=", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlLike(String value) {
			addCriterion("item_url like", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlNotLike(String value) {
			addCriterion("item_url not like", value, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlIn(List<String> values) {
			addCriterion("item_url in", values, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlNotIn(List<String> values) {
			addCriterion("item_url not in", values, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlBetween(String value1, String value2) {
			addCriterion("item_url between", value1, value2, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemUrlNotBetween(String value1, String value2) {
			addCriterion("item_url not between", value1, value2, "itemUrl");
			return (Criteria) this;
		}

		public Criteria andItemDirIsNull() {
			addCriterion("item_dir is null");
			return (Criteria) this;
		}

		public Criteria andItemDirIsNotNull() {
			addCriterion("item_dir is not null");
			return (Criteria) this;
		}

		public Criteria andItemDirEqualTo(String value) {
			addCriterion("item_dir =", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirNotEqualTo(String value) {
			addCriterion("item_dir <>", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirGreaterThan(String value) {
			addCriterion("item_dir >", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirGreaterThanOrEqualTo(String value) {
			addCriterion("item_dir >=", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirLessThan(String value) {
			addCriterion("item_dir <", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirLessThanOrEqualTo(String value) {
			addCriterion("item_dir <=", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirLike(String value) {
			addCriterion("item_dir like", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirNotLike(String value) {
			addCriterion("item_dir not like", value, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirIn(List<String> values) {
			addCriterion("item_dir in", values, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirNotIn(List<String> values) {
			addCriterion("item_dir not in", values, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirBetween(String value1, String value2) {
			addCriterion("item_dir between", value1, value2, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemDirNotBetween(String value1, String value2) {
			addCriterion("item_dir not between", value1, value2, "itemDir");
			return (Criteria) this;
		}

		public Criteria andItemLengthIsNull() {
			addCriterion("item_length is null");
			return (Criteria) this;
		}

		public Criteria andItemLengthIsNotNull() {
			addCriterion("item_length is not null");
			return (Criteria) this;
		}

		public Criteria andItemLengthEqualTo(Long value) {
			addCriterion("item_length =", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthNotEqualTo(Long value) {
			addCriterion("item_length <>", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthGreaterThan(Long value) {
			addCriterion("item_length >", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthGreaterThanOrEqualTo(Long value) {
			addCriterion("item_length >=", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthLessThan(Long value) {
			addCriterion("item_length <", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthLessThanOrEqualTo(Long value) {
			addCriterion("item_length <=", value, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthIn(List<Long> values) {
			addCriterion("item_length in", values, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthNotIn(List<Long> values) {
			addCriterion("item_length not in", values, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthBetween(Long value1, Long value2) {
			addCriterion("item_length between", value1, value2, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemLengthNotBetween(Long value1, Long value2) {
			addCriterion("item_length not between", value1, value2, "itemLength");
			return (Criteria) this;
		}

		public Criteria andItemTypeIsNull() {
			addCriterion("item_type is null");
			return (Criteria) this;
		}

		public Criteria andItemTypeIsNotNull() {
			addCriterion("item_type is not null");
			return (Criteria) this;
		}

		public Criteria andItemTypeEqualTo(Integer value) {
			addCriterion("item_type =", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotEqualTo(Integer value) {
			addCriterion("item_type <>", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeGreaterThan(Integer value) {
			addCriterion("item_type >", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_type >=", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeLessThan(Integer value) {
			addCriterion("item_type <", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeLessThanOrEqualTo(Integer value) {
			addCriterion("item_type <=", value, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeIn(List<Integer> values) {
			addCriterion("item_type in", values, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotIn(List<Integer> values) {
			addCriterion("item_type not in", values, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeBetween(Integer value1, Integer value2) {
			addCriterion("item_type between", value1, value2, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("item_type not between", value1, value2, "itemType");
			return (Criteria) this;
		}

		public Criteria andItemOrderIsNull() {
			addCriterion("item_order is null");
			return (Criteria) this;
		}

		public Criteria andItemOrderIsNotNull() {
			addCriterion("item_order is not null");
			return (Criteria) this;
		}

		public Criteria andItemOrderEqualTo(Integer value) {
			addCriterion("item_order =", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderNotEqualTo(Integer value) {
			addCriterion("item_order <>", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderGreaterThan(Integer value) {
			addCriterion("item_order >", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_order >=", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderLessThan(Integer value) {
			addCriterion("item_order <", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderLessThanOrEqualTo(Integer value) {
			addCriterion("item_order <=", value, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderIn(List<Integer> values) {
			addCriterion("item_order in", values, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderNotIn(List<Integer> values) {
			addCriterion("item_order not in", values, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderBetween(Integer value1, Integer value2) {
			addCriterion("item_order between", value1, value2, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("item_order not between", value1, value2, "itemOrder");
			return (Criteria) this;
		}

		public Criteria andItemCoverIsNull() {
			addCriterion("item_cover is null");
			return (Criteria) this;
		}

		public Criteria andItemCoverIsNotNull() {
			addCriterion("item_cover is not null");
			return (Criteria) this;
		}

		public Criteria andItemCoverEqualTo(String value) {
			addCriterion("item_cover =", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverNotEqualTo(String value) {
			addCriterion("item_cover <>", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverGreaterThan(String value) {
			addCriterion("item_cover >", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverGreaterThanOrEqualTo(String value) {
			addCriterion("item_cover >=", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverLessThan(String value) {
			addCriterion("item_cover <", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverLessThanOrEqualTo(String value) {
			addCriterion("item_cover <=", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverLike(String value) {
			addCriterion("item_cover like", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverNotLike(String value) {
			addCriterion("item_cover not like", value, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverIn(List<String> values) {
			addCriterion("item_cover in", values, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverNotIn(List<String> values) {
			addCriterion("item_cover not in", values, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverBetween(String value1, String value2) {
			addCriterion("item_cover between", value1, value2, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemCoverNotBetween(String value1, String value2) {
			addCriterion("item_cover not between", value1, value2, "itemCover");
			return (Criteria) this;
		}

		public Criteria andItemStartIsNull() {
			addCriterion("item_start is null");
			return (Criteria) this;
		}

		public Criteria andItemStartIsNotNull() {
			addCriterion("item_start is not null");
			return (Criteria) this;
		}

		public Criteria andItemStartEqualTo(Long value) {
			addCriterion("item_start =", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartNotEqualTo(Long value) {
			addCriterion("item_start <>", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartGreaterThan(Long value) {
			addCriterion("item_start >", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartGreaterThanOrEqualTo(Long value) {
			addCriterion("item_start >=", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartLessThan(Long value) {
			addCriterion("item_start <", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartLessThanOrEqualTo(Long value) {
			addCriterion("item_start <=", value, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartIn(List<Long> values) {
			addCriterion("item_start in", values, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartNotIn(List<Long> values) {
			addCriterion("item_start not in", values, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartBetween(Long value1, Long value2) {
			addCriterion("item_start between", value1, value2, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemStartNotBetween(Long value1, Long value2) {
			addCriterion("item_start not between", value1, value2, "itemStart");
			return (Criteria) this;
		}

		public Criteria andItemEndIsNull() {
			addCriterion("item_end is null");
			return (Criteria) this;
		}

		public Criteria andItemEndIsNotNull() {
			addCriterion("item_end is not null");
			return (Criteria) this;
		}

		public Criteria andItemEndEqualTo(Long value) {
			addCriterion("item_end =", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndNotEqualTo(Long value) {
			addCriterion("item_end <>", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndGreaterThan(Long value) {
			addCriterion("item_end >", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndGreaterThanOrEqualTo(Long value) {
			addCriterion("item_end >=", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndLessThan(Long value) {
			addCriterion("item_end <", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndLessThanOrEqualTo(Long value) {
			addCriterion("item_end <=", value, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndIn(List<Long> values) {
			addCriterion("item_end in", values, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndNotIn(List<Long> values) {
			addCriterion("item_end not in", values, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndBetween(Long value1, Long value2) {
			addCriterion("item_end between", value1, value2, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemEndNotBetween(Long value1, Long value2) {
			addCriterion("item_end not between", value1, value2, "itemEnd");
			return (Criteria) this;
		}

		public Criteria andItemWidthIsNull() {
			addCriterion("item_width is null");
			return (Criteria) this;
		}

		public Criteria andItemWidthIsNotNull() {
			addCriterion("item_width is not null");
			return (Criteria) this;
		}

		public Criteria andItemWidthEqualTo(Integer value) {
			addCriterion("item_width =", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthNotEqualTo(Integer value) {
			addCriterion("item_width <>", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthGreaterThan(Integer value) {
			addCriterion("item_width >", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_width >=", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthLessThan(Integer value) {
			addCriterion("item_width <", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthLessThanOrEqualTo(Integer value) {
			addCriterion("item_width <=", value, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthIn(List<Integer> values) {
			addCriterion("item_width in", values, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthNotIn(List<Integer> values) {
			addCriterion("item_width not in", values, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthBetween(Integer value1, Integer value2) {
			addCriterion("item_width between", value1, value2, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemWidthNotBetween(Integer value1, Integer value2) {
			addCriterion("item_width not between", value1, value2, "itemWidth");
			return (Criteria) this;
		}

		public Criteria andItemHeightIsNull() {
			addCriterion("item_height is null");
			return (Criteria) this;
		}

		public Criteria andItemHeightIsNotNull() {
			addCriterion("item_height is not null");
			return (Criteria) this;
		}

		public Criteria andItemHeightEqualTo(Integer value) {
			addCriterion("item_height =", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightNotEqualTo(Integer value) {
			addCriterion("item_height <>", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightGreaterThan(Integer value) {
			addCriterion("item_height >", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_height >=", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightLessThan(Integer value) {
			addCriterion("item_height <", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightLessThanOrEqualTo(Integer value) {
			addCriterion("item_height <=", value, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightIn(List<Integer> values) {
			addCriterion("item_height in", values, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightNotIn(List<Integer> values) {
			addCriterion("item_height not in", values, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightBetween(Integer value1, Integer value2) {
			addCriterion("item_height between", value1, value2, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andItemHeightNotBetween(Integer value1, Integer value2) {
			addCriterion("item_height not between", value1, value2, "itemHeight");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNull() {
			addCriterion("create_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNotNull() {
			addCriterion("create_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateIdEqualTo(String value) {
			addCriterion("create_id =", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotEqualTo(String value) {
			addCriterion("create_id <>", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThan(String value) {
			addCriterion("create_id >", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
			addCriterion("create_id >=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThan(String value) {
			addCriterion("create_id <", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThanOrEqualTo(String value) {
			addCriterion("create_id <=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLike(String value) {
			addCriterion("create_id like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotLike(String value) {
			addCriterion("create_id not like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdIn(List<String> values) {
			addCriterion("create_id in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotIn(List<String> values) {
			addCriterion("create_id not in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdBetween(String value1, String value2) {
			addCriterion("create_id between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotBetween(String value1, String value2) {
			addCriterion("create_id not between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("update_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("update_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("update_id =", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("update_id <>", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("update_id >", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("update_id >=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("update_id <", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("update_id <=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("update_id like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("update_id not like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIn(List<String> values) {
			addCriterion("update_id in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotIn(List<String> values) {
			addCriterion("update_id not in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("update_id between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("update_id not between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameIsNull() {
			addCriterion("item_original_name is null");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameIsNotNull() {
			addCriterion("item_original_name is not null");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameEqualTo(String value) {
			addCriterion("item_original_name =", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameNotEqualTo(String value) {
			addCriterion("item_original_name <>", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameGreaterThan(String value) {
			addCriterion("item_original_name >", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameGreaterThanOrEqualTo(String value) {
			addCriterion("item_original_name >=", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameLessThan(String value) {
			addCriterion("item_original_name <", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameLessThanOrEqualTo(String value) {
			addCriterion("item_original_name <=", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameLike(String value) {
			addCriterion("item_original_name like", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameNotLike(String value) {
			addCriterion("item_original_name not like", value, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameIn(List<String> values) {
			addCriterion("item_original_name in", values, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameNotIn(List<String> values) {
			addCriterion("item_original_name not in", values, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameBetween(String value1, String value2) {
			addCriterion("item_original_name between", value1, value2, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemOriginalNameNotBetween(String value1, String value2) {
			addCriterion("item_original_name not between", value1, value2, "itemOriginalName");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusIsNull() {
			addCriterion("item_convert_status is null");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusIsNotNull() {
			addCriterion("item_convert_status is not null");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusEqualTo(Integer value) {
			addCriterion("item_convert_status =", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusNotEqualTo(Integer value) {
			addCriterion("item_convert_status <>", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusGreaterThan(Integer value) {
			addCriterion("item_convert_status >", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("item_convert_status >=", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusLessThan(Integer value) {
			addCriterion("item_convert_status <", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusLessThanOrEqualTo(Integer value) {
			addCriterion("item_convert_status <=", value, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusIn(List<Integer> values) {
			addCriterion("item_convert_status in", values, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusNotIn(List<Integer> values) {
			addCriterion("item_convert_status not in", values, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusBetween(Integer value1, Integer value2) {
			addCriterion("item_convert_status between", value1, value2, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemConvertStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("item_convert_status not between", value1, value2, "itemConvertStatus");
			return (Criteria) this;
		}

		public Criteria andItemJobIdIsNull() {
			addCriterion("item_job_id is null");
			return (Criteria) this;
		}

		public Criteria andItemJobIdIsNotNull() {
			addCriterion("item_job_id is not null");
			return (Criteria) this;
		}

		public Criteria andItemJobIdEqualTo(String value) {
			addCriterion("item_job_id =", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdNotEqualTo(String value) {
			addCriterion("item_job_id <>", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdGreaterThan(String value) {
			addCriterion("item_job_id >", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdGreaterThanOrEqualTo(String value) {
			addCriterion("item_job_id >=", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdLessThan(String value) {
			addCriterion("item_job_id <", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdLessThanOrEqualTo(String value) {
			addCriterion("item_job_id <=", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdLike(String value) {
			addCriterion("item_job_id like", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdNotLike(String value) {
			addCriterion("item_job_id not like", value, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdIn(List<String> values) {
			addCriterion("item_job_id in", values, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdNotIn(List<String> values) {
			addCriterion("item_job_id not in", values, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdBetween(String value1, String value2) {
			addCriterion("item_job_id between", value1, value2, "itemJobId");
			return (Criteria) this;
		}

		public Criteria andItemJobIdNotBetween(String value1, String value2) {
			addCriterion("item_job_id not between", value1, value2, "itemJobId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_attachment_media_item
	 * @mbggenerated  Thu Feb 23 11:31:19 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_attachment_media_item
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 21 13:33:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}