package com.deodio.elearning.persistence.model;

import java.util.Date;

public class CourseTrainee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.item_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.item_type
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Short itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.create_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.create_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.update_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Object updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.update_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.trainee_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private String traineeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.purchase_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Date purchaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.deadline_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Date deadlineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.is_charge
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Short isCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.is_free
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Short isFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.chapter_count
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Short chapterCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.chapter_finish
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private Short chapterFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trainee_course.account_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    private String accountId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.id
     *
     * @return the value of t_trainee_course.id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.id
     *
     * @param id the value for t_trainee_course.id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.item_id
     *
     * @return the value of t_trainee_course.item_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.item_id
     *
     * @param itemId the value for t_trainee_course.item_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.item_type
     *
     * @return the value of t_trainee_course.item_type
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Short getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.item_type
     *
     * @param itemType the value for t_trainee_course.item_type
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setItemType(Short itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.create_id
     *
     * @return the value of t_trainee_course.create_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.create_id
     *
     * @param createId the value for t_trainee_course.create_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.create_time
     *
     * @return the value of t_trainee_course.create_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.create_time
     *
     * @param createTime the value for t_trainee_course.create_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.update_id
     *
     * @return the value of t_trainee_course.update_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Object getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.update_id
     *
     * @param updateId the value for t_trainee_course.update_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setUpdateId(Object updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.update_time
     *
     * @return the value of t_trainee_course.update_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.update_time
     *
     * @param updateTime the value for t_trainee_course.update_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.trainee_id
     *
     * @return the value of t_trainee_course.trainee_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public String getTraineeId() {
        return traineeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.trainee_id
     *
     * @param traineeId the value for t_trainee_course.trainee_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setTraineeId(String traineeId) {
        this.traineeId = traineeId == null ? null : traineeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.purchase_time
     *
     * @return the value of t_trainee_course.purchase_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.purchase_time
     *
     * @param purchaseTime the value for t_trainee_course.purchase_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.deadline_time
     *
     * @return the value of t_trainee_course.deadline_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Date getDeadlineTime() {
        return deadlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.deadline_time
     *
     * @param deadlineTime the value for t_trainee_course.deadline_time
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setDeadlineTime(Date deadlineTime) {
        this.deadlineTime = deadlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.is_charge
     *
     * @return the value of t_trainee_course.is_charge
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Short getIsCharge() {
        return isCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.is_charge
     *
     * @param isCharge the value for t_trainee_course.is_charge
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setIsCharge(Short isCharge) {
        this.isCharge = isCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.is_free
     *
     * @return the value of t_trainee_course.is_free
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Short getIsFree() {
        return isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.is_free
     *
     * @param isFree the value for t_trainee_course.is_free
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setIsFree(Short isFree) {
        this.isFree = isFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.chapter_count
     *
     * @return the value of t_trainee_course.chapter_count
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Short getChapterCount() {
        return chapterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.chapter_count
     *
     * @param chapterCount the value for t_trainee_course.chapter_count
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setChapterCount(Short chapterCount) {
        this.chapterCount = chapterCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.chapter_finish
     *
     * @return the value of t_trainee_course.chapter_finish
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public Short getChapterFinish() {
        return chapterFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.chapter_finish
     *
     * @param chapterFinish the value for t_trainee_course.chapter_finish
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setChapterFinish(Short chapterFinish) {
        this.chapterFinish = chapterFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trainee_course.account_id
     *
     * @return the value of t_trainee_course.account_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trainee_course.account_id
     *
     * @param accountId the value for t_trainee_course.account_id
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }
}