package com.deodio.elearning.persistence.model;

import java.util.Date;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_name
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_description
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_objective
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseObjective;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.is_public
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Integer isPublic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_cover_img
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseCoverImg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.create_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.update_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.create_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.update_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_type
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Integer courseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.is_publish
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Short isPublish;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.start_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.expire_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Date expireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_infomartion
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseInfomartion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.account_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.trainee_num
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Integer traineeNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.course_owner
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String courseOwner;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.is_edit
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private Integer isEdit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_course.group_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	private String groupId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.id
	 * @return  the value of t_course.id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.id
	 * @param id  the value for t_course.id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_name
	 * @return  the value of t_course.course_name
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseName() {
		return courseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_name
	 * @param courseName  the value for t_course.course_name
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseName(String courseName) {
		this.courseName = courseName == null ? null : courseName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_description
	 * @return  the value of t_course.course_description
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseDescription() {
		return courseDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_description
	 * @param courseDescription  the value for t_course.course_description
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseDescription(String courseDescription) {
		this.courseDescription = courseDescription == null ? null : courseDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_objective
	 * @return  the value of t_course.course_objective
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseObjective() {
		return courseObjective;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_objective
	 * @param courseObjective  the value for t_course.course_objective
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseObjective(String courseObjective) {
		this.courseObjective = courseObjective == null ? null : courseObjective.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.is_public
	 * @return  the value of t_course.is_public
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Integer getIsPublic() {
		return isPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.is_public
	 * @param isPublic  the value for t_course.is_public
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setIsPublic(Integer isPublic) {
		this.isPublic = isPublic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_cover_img
	 * @return  the value of t_course.course_cover_img
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseCoverImg() {
		return courseCoverImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_cover_img
	 * @param courseCoverImg  the value for t_course.course_cover_img
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseCoverImg(String courseCoverImg) {
		this.courseCoverImg = courseCoverImg == null ? null : courseCoverImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.create_id
	 * @return  the value of t_course.create_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.create_id
	 * @param createId  the value for t_course.create_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.update_id
	 * @return  the value of t_course.update_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.update_id
	 * @param updateId  the value for t_course.update_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.create_time
	 * @return  the value of t_course.create_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.create_time
	 * @param createTime  the value for t_course.create_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.update_time
	 * @return  the value of t_course.update_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.update_time
	 * @param updateTime  the value for t_course.update_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_type
	 * @return  the value of t_course.course_type
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Integer getCourseType() {
		return courseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_type
	 * @param courseType  the value for t_course.course_type
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseType(Integer courseType) {
		this.courseType = courseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.is_publish
	 * @return  the value of t_course.is_publish
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Short getIsPublish() {
		return isPublish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.is_publish
	 * @param isPublish  the value for t_course.is_publish
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setIsPublish(Short isPublish) {
		this.isPublish = isPublish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.start_time
	 * @return  the value of t_course.start_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.start_time
	 * @param startTime  the value for t_course.start_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.expire_time
	 * @return  the value of t_course.expire_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Date getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.expire_time
	 * @param expireTime  the value for t_course.expire_time
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_infomartion
	 * @return  the value of t_course.course_infomartion
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseInfomartion() {
		return courseInfomartion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_infomartion
	 * @param courseInfomartion  the value for t_course.course_infomartion
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseInfomartion(String courseInfomartion) {
		this.courseInfomartion = courseInfomartion == null ? null : courseInfomartion.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.account_id
	 * @return  the value of t_course.account_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.account_id
	 * @param accountId  the value for t_course.account_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.trainee_num
	 * @return  the value of t_course.trainee_num
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Integer getTraineeNum() {
		return traineeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.trainee_num
	 * @param traineeNum  the value for t_course.trainee_num
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setTraineeNum(Integer traineeNum) {
		this.traineeNum = traineeNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.course_owner
	 * @return  the value of t_course.course_owner
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getCourseOwner() {
		return courseOwner;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.course_owner
	 * @param courseOwner  the value for t_course.course_owner
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setCourseOwner(String courseOwner) {
		this.courseOwner = courseOwner == null ? null : courseOwner.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.is_edit
	 * @return  the value of t_course.is_edit
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public Integer getIsEdit() {
		return isEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.is_edit
	 * @param isEdit  the value for t_course.is_edit
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setIsEdit(Integer isEdit) {
		this.isEdit = isEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_course.group_id
	 * @return  the value of t_course.group_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_course.group_id
	 * @param groupId  the value for t_course.group_id
	 * @mbg.generated  Tue Jul 10 14:30:23 CST 2018
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId == null ? null : groupId.trim();
	}
}