package com.deodio.elearning.persistence.model;

import java.util.Date;

public class PresentationModelExternal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.presentation_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private String presentationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.create_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.create_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.update_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.update_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_presentation_model_external.external_type
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    private Short externalType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.id
     *
     * @return the value of t_presentation_model_external.id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.id
     *
     * @param id the value for t_presentation_model_external.id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.presentation_id
     *
     * @return the value of t_presentation_model_external.presentation_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public String getPresentationId() {
        return presentationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.presentation_id
     *
     * @param presentationId the value for t_presentation_model_external.presentation_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setPresentationId(String presentationId) {
        this.presentationId = presentationId == null ? null : presentationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.create_id
     *
     * @return the value of t_presentation_model_external.create_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.create_id
     *
     * @param createId the value for t_presentation_model_external.create_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.create_time
     *
     * @return the value of t_presentation_model_external.create_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.create_time
     *
     * @param createTime the value for t_presentation_model_external.create_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.update_id
     *
     * @return the value of t_presentation_model_external.update_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.update_id
     *
     * @param updateId the value for t_presentation_model_external.update_id
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.update_time
     *
     * @return the value of t_presentation_model_external.update_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.update_time
     *
     * @param updateTime the value for t_presentation_model_external.update_time
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_presentation_model_external.external_type
     *
     * @return the value of t_presentation_model_external.external_type
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public Short getExternalType() {
        return externalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_presentation_model_external.external_type
     *
     * @param externalType the value for t_presentation_model_external.external_type
     *
     * @mbggenerated Wed Jul 13 14:41:05 CST 2016
     */
    public void setExternalType(Short externalType) {
        this.externalType = externalType;
    }
}