package com.deodio.elearning.persistence.model;

import java.util.Date;

public class PresentationDiscussionReply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_presentation_discussion_reply.id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_presentation_discussion_reply.reply_content
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	private String replyContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_presentation_discussion_reply.reply_user_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	private String replyUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_presentation_discussion_reply.reply_date
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	private Date replyDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_presentation_discussion_reply.presentation_dis_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	private String presentationDisId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_presentation_discussion_reply.id
	 * @return  the value of t_presentation_discussion_reply.id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_presentation_discussion_reply.id
	 * @param id  the value for t_presentation_discussion_reply.id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_presentation_discussion_reply.reply_content
	 * @return  the value of t_presentation_discussion_reply.reply_content
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public String getReplyContent() {
		return replyContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_presentation_discussion_reply.reply_content
	 * @param replyContent  the value for t_presentation_discussion_reply.reply_content
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent == null ? null : replyContent.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_presentation_discussion_reply.reply_user_id
	 * @return  the value of t_presentation_discussion_reply.reply_user_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public String getReplyUserId() {
		return replyUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_presentation_discussion_reply.reply_user_id
	 * @param replyUserId  the value for t_presentation_discussion_reply.reply_user_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public void setReplyUserId(String replyUserId) {
		this.replyUserId = replyUserId == null ? null : replyUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_presentation_discussion_reply.reply_date
	 * @return  the value of t_presentation_discussion_reply.reply_date
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public Date getReplyDate() {
		return replyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_presentation_discussion_reply.reply_date
	 * @param replyDate  the value for t_presentation_discussion_reply.reply_date
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public void setReplyDate(Date replyDate) {
		this.replyDate = replyDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_presentation_discussion_reply.presentation_dis_id
	 * @return  the value of t_presentation_discussion_reply.presentation_dis_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public String getPresentationDisId() {
		return presentationDisId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_presentation_discussion_reply.presentation_dis_id
	 * @param presentationDisId  the value for t_presentation_discussion_reply.presentation_dis_id
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	public void setPresentationDisId(String presentationDisId) {
		this.presentationDisId = presentationDisId == null ? null : presentationDisId.trim();
	}
}