package com.deodio.elearning.persistence.model;

import java.util.Date;

public class QuizBanks {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.quiz_bank_name
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String quizBankName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.quiz_bank_desc
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String quizBankDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.classification_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String classificationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.account_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.is_private
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private Short isPrivate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.create_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.create_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.update_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_banks.update_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.id
	 * @return  the value of t_quiz_banks.id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.id
	 * @param id  the value for t_quiz_banks.id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.quiz_bank_name
	 * @return  the value of t_quiz_banks.quiz_bank_name
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getQuizBankName() {
		return quizBankName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.quiz_bank_name
	 * @param quizBankName  the value for t_quiz_banks.quiz_bank_name
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setQuizBankName(String quizBankName) {
		this.quizBankName = quizBankName == null ? null : quizBankName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.quiz_bank_desc
	 * @return  the value of t_quiz_banks.quiz_bank_desc
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getQuizBankDesc() {
		return quizBankDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.quiz_bank_desc
	 * @param quizBankDesc  the value for t_quiz_banks.quiz_bank_desc
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setQuizBankDesc(String quizBankDesc) {
		this.quizBankDesc = quizBankDesc == null ? null : quizBankDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.classification_id
	 * @return  the value of t_quiz_banks.classification_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getClassificationId() {
		return classificationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.classification_id
	 * @param classificationId  the value for t_quiz_banks.classification_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setClassificationId(String classificationId) {
		this.classificationId = classificationId == null ? null
				: classificationId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.account_id
	 * @return  the value of t_quiz_banks.account_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.account_id
	 * @param accountId  the value for t_quiz_banks.account_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.is_private
	 * @return  the value of t_quiz_banks.is_private
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public Short getIsPrivate() {
		return isPrivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.is_private
	 * @param isPrivate  the value for t_quiz_banks.is_private
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setIsPrivate(Short isPrivate) {
		this.isPrivate = isPrivate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.create_id
	 * @return  the value of t_quiz_banks.create_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.create_id
	 * @param createId  the value for t_quiz_banks.create_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.create_time
	 * @return  the value of t_quiz_banks.create_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.create_time
	 * @param createTime  the value for t_quiz_banks.create_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.update_id
	 * @return  the value of t_quiz_banks.update_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.update_id
	 * @param updateId  the value for t_quiz_banks.update_id
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_banks.update_time
	 * @return  the value of t_quiz_banks.update_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_banks.update_time
	 * @param updateTime  the value for t_quiz_banks.update_time
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}