package com.deodio.elearning.persistence.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QuizSubjectExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public QuizSubjectExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameIsNull() {
			addCriterion("quiz_subject_name is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameIsNotNull() {
			addCriterion("quiz_subject_name is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameEqualTo(String value) {
			addCriterion("quiz_subject_name =", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameNotEqualTo(String value) {
			addCriterion("quiz_subject_name <>", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameGreaterThan(String value) {
			addCriterion("quiz_subject_name >", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameGreaterThanOrEqualTo(String value) {
			addCriterion("quiz_subject_name >=", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameLessThan(String value) {
			addCriterion("quiz_subject_name <", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameLessThanOrEqualTo(String value) {
			addCriterion("quiz_subject_name <=", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameLike(String value) {
			addCriterion("quiz_subject_name like", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameNotLike(String value) {
			addCriterion("quiz_subject_name not like", value, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameIn(List<String> values) {
			addCriterion("quiz_subject_name in", values, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameNotIn(List<String> values) {
			addCriterion("quiz_subject_name not in", values, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameBetween(String value1, String value2) {
			addCriterion("quiz_subject_name between", value1, value2, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectNameNotBetween(String value1, String value2) {
			addCriterion("quiz_subject_name not between", value1, value2, "quizSubjectName");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNull() {
			addCriterion("create_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateIdIsNotNull() {
			addCriterion("create_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateIdEqualTo(String value) {
			addCriterion("create_id =", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotEqualTo(String value) {
			addCriterion("create_id <>", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThan(String value) {
			addCriterion("create_id >", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdGreaterThanOrEqualTo(String value) {
			addCriterion("create_id >=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThan(String value) {
			addCriterion("create_id <", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLessThanOrEqualTo(String value) {
			addCriterion("create_id <=", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdLike(String value) {
			addCriterion("create_id like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotLike(String value) {
			addCriterion("create_id not like", value, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdIn(List<String> values) {
			addCriterion("create_id in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotIn(List<String> values) {
			addCriterion("create_id not in", values, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdBetween(String value1, String value2) {
			addCriterion("create_id between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andCreateIdNotBetween(String value1, String value2) {
			addCriterion("create_id not between", value1, value2, "createId");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNull() {
			addCriterion("update_id is null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIsNotNull() {
			addCriterion("update_id is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateIdEqualTo(String value) {
			addCriterion("update_id =", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotEqualTo(String value) {
			addCriterion("update_id <>", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThan(String value) {
			addCriterion("update_id >", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
			addCriterion("update_id >=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThan(String value) {
			addCriterion("update_id <", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLessThanOrEqualTo(String value) {
			addCriterion("update_id <=", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdLike(String value) {
			addCriterion("update_id like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotLike(String value) {
			addCriterion("update_id not like", value, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdIn(List<String> values) {
			addCriterion("update_id in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotIn(List<String> values) {
			addCriterion("update_id not in", values, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdBetween(String value1, String value2) {
			addCriterion("update_id between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andUpdateIdNotBetween(String value1, String value2) {
			addCriterion("update_id not between", value1, value2, "updateId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNull() {
			addCriterion("account_id is null");
			return (Criteria) this;
		}

		public Criteria andAccountIdIsNotNull() {
			addCriterion("account_id is not null");
			return (Criteria) this;
		}

		public Criteria andAccountIdEqualTo(String value) {
			addCriterion("account_id =", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotEqualTo(String value) {
			addCriterion("account_id <>", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThan(String value) {
			addCriterion("account_id >", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
			addCriterion("account_id >=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThan(String value) {
			addCriterion("account_id <", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLessThanOrEqualTo(String value) {
			addCriterion("account_id <=", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdLike(String value) {
			addCriterion("account_id like", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotLike(String value) {
			addCriterion("account_id not like", value, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdIn(List<String> values) {
			addCriterion("account_id in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotIn(List<String> values) {
			addCriterion("account_id not in", values, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdBetween(String value1, String value2) {
			addCriterion("account_id between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andAccountIdNotBetween(String value1, String value2) {
			addCriterion("account_id not between", value1, value2, "accountId");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeIsNull() {
			addCriterion("quiz_subject_type is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeIsNotNull() {
			addCriterion("quiz_subject_type is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeEqualTo(Integer value) {
			addCriterion("quiz_subject_type =", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeNotEqualTo(Integer value) {
			addCriterion("quiz_subject_type <>", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeGreaterThan(Integer value) {
			addCriterion("quiz_subject_type >", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_type >=", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeLessThan(Integer value) {
			addCriterion("quiz_subject_type <", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_type <=", value, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeIn(List<Integer> values) {
			addCriterion("quiz_subject_type in", values, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeNotIn(List<Integer> values) {
			addCriterion("quiz_subject_type not in", values, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_type between", value1, value2, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_type not between", value1, value2, "quizSubjectType");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdIsNull() {
			addCriterion("quiz_bank_id is null");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdIsNotNull() {
			addCriterion("quiz_bank_id is not null");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdEqualTo(String value) {
			addCriterion("quiz_bank_id =", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdNotEqualTo(String value) {
			addCriterion("quiz_bank_id <>", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdGreaterThan(String value) {
			addCriterion("quiz_bank_id >", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdGreaterThanOrEqualTo(String value) {
			addCriterion("quiz_bank_id >=", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdLessThan(String value) {
			addCriterion("quiz_bank_id <", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdLessThanOrEqualTo(String value) {
			addCriterion("quiz_bank_id <=", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdLike(String value) {
			addCriterion("quiz_bank_id like", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdNotLike(String value) {
			addCriterion("quiz_bank_id not like", value, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdIn(List<String> values) {
			addCriterion("quiz_bank_id in", values, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdNotIn(List<String> values) {
			addCriterion("quiz_bank_id not in", values, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdBetween(String value1, String value2) {
			addCriterion("quiz_bank_id between", value1, value2, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizBankIdNotBetween(String value1, String value2) {
			addCriterion("quiz_bank_id not between", value1, value2, "quizBankId");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelIsNull() {
			addCriterion("quiz_subject_level is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelIsNotNull() {
			addCriterion("quiz_subject_level is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelEqualTo(Integer value) {
			addCriterion("quiz_subject_level =", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelNotEqualTo(Integer value) {
			addCriterion("quiz_subject_level <>", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelGreaterThan(Integer value) {
			addCriterion("quiz_subject_level >", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_level >=", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelLessThan(Integer value) {
			addCriterion("quiz_subject_level <", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_level <=", value, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelIn(List<Integer> values) {
			addCriterion("quiz_subject_level in", values, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelNotIn(List<Integer> values) {
			addCriterion("quiz_subject_level not in", values, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_level between", value1, value2, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_level not between", value1, value2, "quizSubjectLevel");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreIsNull() {
			addCriterion("quiz_subject_score is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreIsNotNull() {
			addCriterion("quiz_subject_score is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreEqualTo(Integer value) {
			addCriterion("quiz_subject_score =", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreNotEqualTo(Integer value) {
			addCriterion("quiz_subject_score <>", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreGreaterThan(Integer value) {
			addCriterion("quiz_subject_score >", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_score >=", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreLessThan(Integer value) {
			addCriterion("quiz_subject_score <", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_score <=", value, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreIn(List<Integer> values) {
			addCriterion("quiz_subject_score in", values, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreNotIn(List<Integer> values) {
			addCriterion("quiz_subject_score not in", values, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_score between", value1, value2, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_score not between", value1, value2, "quizSubjectScore");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeIsNull() {
			addCriterion("quiz_subject_expire_time is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeIsNotNull() {
			addCriterion("quiz_subject_expire_time is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeEqualTo(Date value) {
			addCriterion("quiz_subject_expire_time =", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeNotEqualTo(Date value) {
			addCriterion("quiz_subject_expire_time <>", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeGreaterThan(Date value) {
			addCriterion("quiz_subject_expire_time >", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("quiz_subject_expire_time >=", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeLessThan(Date value) {
			addCriterion("quiz_subject_expire_time <", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeLessThanOrEqualTo(Date value) {
			addCriterion("quiz_subject_expire_time <=", value, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeIn(List<Date> values) {
			addCriterion("quiz_subject_expire_time in", values, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeNotIn(List<Date> values) {
			addCriterion("quiz_subject_expire_time not in", values, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeBetween(Date value1, Date value2) {
			addCriterion("quiz_subject_expire_time between", value1, value2, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectExpireTimeNotBetween(Date value1, Date value2) {
			addCriterion("quiz_subject_expire_time not between", value1, value2, "quizSubjectExpireTime");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleIsNull() {
			addCriterion("quiz_subject_visible is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleIsNotNull() {
			addCriterion("quiz_subject_visible is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleEqualTo(Integer value) {
			addCriterion("quiz_subject_visible =", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleNotEqualTo(Integer value) {
			addCriterion("quiz_subject_visible <>", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleGreaterThan(Integer value) {
			addCriterion("quiz_subject_visible >", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_visible >=", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleLessThan(Integer value) {
			addCriterion("quiz_subject_visible <", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_visible <=", value, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleIn(List<Integer> values) {
			addCriterion("quiz_subject_visible in", values, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleNotIn(List<Integer> values) {
			addCriterion("quiz_subject_visible not in", values, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_visible between", value1, value2, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectVisibleNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_visible not between", value1, value2, "quizSubjectVisible");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromIsNull() {
			addCriterion("quiz_subject_from is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromIsNotNull() {
			addCriterion("quiz_subject_from is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromEqualTo(Integer value) {
			addCriterion("quiz_subject_from =", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromNotEqualTo(Integer value) {
			addCriterion("quiz_subject_from <>", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromGreaterThan(Integer value) {
			addCriterion("quiz_subject_from >", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_from >=", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromLessThan(Integer value) {
			addCriterion("quiz_subject_from <", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_from <=", value, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromIn(List<Integer> values) {
			addCriterion("quiz_subject_from in", values, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromNotIn(List<Integer> values) {
			addCriterion("quiz_subject_from not in", values, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_from between", value1, value2, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectFromNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_from not between", value1, value2, "quizSubjectFrom");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishIsNull() {
			addCriterion("quiz_subject_is_publish is null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishIsNotNull() {
			addCriterion("quiz_subject_is_publish is not null");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishEqualTo(Integer value) {
			addCriterion("quiz_subject_is_publish =", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishNotEqualTo(Integer value) {
			addCriterion("quiz_subject_is_publish <>", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishGreaterThan(Integer value) {
			addCriterion("quiz_subject_is_publish >", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishGreaterThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_is_publish >=", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishLessThan(Integer value) {
			addCriterion("quiz_subject_is_publish <", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishLessThanOrEqualTo(Integer value) {
			addCriterion("quiz_subject_is_publish <=", value, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishIn(List<Integer> values) {
			addCriterion("quiz_subject_is_publish in", values, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishNotIn(List<Integer> values) {
			addCriterion("quiz_subject_is_publish not in", values, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_is_publish between", value1, value2, "quizSubjectIsPublish");
			return (Criteria) this;
		}

		public Criteria andQuizSubjectIsPublishNotBetween(Integer value1, Integer value2) {
			addCriterion("quiz_subject_is_publish not between", value1, value2, "quizSubjectIsPublish");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_quiz_subject
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 20 17:57:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}