package com.deodio.elearning.persistence.model;

import java.util.ArrayList;
import java.util.List;

public class QuizAutoRuleSubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public QuizAutoRuleSubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIsNull() {
            addCriterion("subject_type is null");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIsNotNull() {
            addCriterion("subject_type is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeEqualTo(Integer value) {
            addCriterion("subject_type =", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotEqualTo(Integer value) {
            addCriterion("subject_type <>", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeGreaterThan(Integer value) {
            addCriterion("subject_type >", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_type >=", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeLessThan(Integer value) {
            addCriterion("subject_type <", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeLessThanOrEqualTo(Integer value) {
            addCriterion("subject_type <=", value, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeIn(List<Integer> values) {
            addCriterion("subject_type in", values, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotIn(List<Integer> values) {
            addCriterion("subject_type not in", values, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeBetween(Integer value1, Integer value2) {
            addCriterion("subject_type between", value1, value2, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_type not between", value1, value2, "subjectType");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderIsNull() {
            addCriterion("subject_order is null");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderIsNotNull() {
            addCriterion("subject_order is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderEqualTo(Integer value) {
            addCriterion("subject_order =", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderNotEqualTo(Integer value) {
            addCriterion("subject_order <>", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderGreaterThan(Integer value) {
            addCriterion("subject_order >", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_order >=", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderLessThan(Integer value) {
            addCriterion("subject_order <", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderLessThanOrEqualTo(Integer value) {
            addCriterion("subject_order <=", value, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderIn(List<Integer> values) {
            addCriterion("subject_order in", values, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderNotIn(List<Integer> values) {
            addCriterion("subject_order not in", values, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderBetween(Integer value1, Integer value2) {
            addCriterion("subject_order between", value1, value2, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_order not between", value1, value2, "subjectOrder");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreIsNull() {
            addCriterion("subject_score is null");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreIsNotNull() {
            addCriterion("subject_score is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreEqualTo(Integer value) {
            addCriterion("subject_score =", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreNotEqualTo(Integer value) {
            addCriterion("subject_score <>", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreGreaterThan(Integer value) {
            addCriterion("subject_score >", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_score >=", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreLessThan(Integer value) {
            addCriterion("subject_score <", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreLessThanOrEqualTo(Integer value) {
            addCriterion("subject_score <=", value, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreIn(List<Integer> values) {
            addCriterion("subject_score in", values, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreNotIn(List<Integer> values) {
            addCriterion("subject_score not in", values, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreBetween(Integer value1, Integer value2) {
            addCriterion("subject_score between", value1, value2, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_score not between", value1, value2, "subjectScore");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountIsNull() {
            addCriterion("subject_items_count is null");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountIsNotNull() {
            addCriterion("subject_items_count is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountEqualTo(Integer value) {
            addCriterion("subject_items_count =", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountNotEqualTo(Integer value) {
            addCriterion("subject_items_count <>", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountGreaterThan(Integer value) {
            addCriterion("subject_items_count >", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("subject_items_count >=", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountLessThan(Integer value) {
            addCriterion("subject_items_count <", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountLessThanOrEqualTo(Integer value) {
            addCriterion("subject_items_count <=", value, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountIn(List<Integer> values) {
            addCriterion("subject_items_count in", values, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountNotIn(List<Integer> values) {
            addCriterion("subject_items_count not in", values, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountBetween(Integer value1, Integer value2) {
            addCriterion("subject_items_count between", value1, value2, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectItemsCountNotBetween(Integer value1, Integer value2) {
            addCriterion("subject_items_count not between", value1, value2, "subjectItemsCount");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkIsNull() {
            addCriterion("subject_remark is null");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkIsNotNull() {
            addCriterion("subject_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkEqualTo(String value) {
            addCriterion("subject_remark =", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkNotEqualTo(String value) {
            addCriterion("subject_remark <>", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkGreaterThan(String value) {
            addCriterion("subject_remark >", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("subject_remark >=", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkLessThan(String value) {
            addCriterion("subject_remark <", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkLessThanOrEqualTo(String value) {
            addCriterion("subject_remark <=", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkLike(String value) {
            addCriterion("subject_remark like", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkNotLike(String value) {
            addCriterion("subject_remark not like", value, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkIn(List<String> values) {
            addCriterion("subject_remark in", values, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkNotIn(List<String> values) {
            addCriterion("subject_remark not in", values, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkBetween(String value1, String value2) {
            addCriterion("subject_remark between", value1, value2, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andSubjectRemarkNotBetween(String value1, String value2) {
            addCriterion("subject_remark not between", value1, value2, "subjectRemark");
            return (Criteria) this;
        }

        public Criteria andQuizIdIsNull() {
            addCriterion("quiz_id is null");
            return (Criteria) this;
        }

        public Criteria andQuizIdIsNotNull() {
            addCriterion("quiz_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuizIdEqualTo(String value) {
            addCriterion("quiz_id =", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdNotEqualTo(String value) {
            addCriterion("quiz_id <>", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdGreaterThan(String value) {
            addCriterion("quiz_id >", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdGreaterThanOrEqualTo(String value) {
            addCriterion("quiz_id >=", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdLessThan(String value) {
            addCriterion("quiz_id <", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdLessThanOrEqualTo(String value) {
            addCriterion("quiz_id <=", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdLike(String value) {
            addCriterion("quiz_id like", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdNotLike(String value) {
            addCriterion("quiz_id not like", value, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdIn(List<String> values) {
            addCriterion("quiz_id in", values, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdNotIn(List<String> values) {
            addCriterion("quiz_id not in", values, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdBetween(String value1, String value2) {
            addCriterion("quiz_id between", value1, value2, "quizId");
            return (Criteria) this;
        }

        public Criteria andQuizIdNotBetween(String value1, String value2) {
            addCriterion("quiz_id not between", value1, value2, "quizId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated do_not_delete_during_merge Fri May 27 14:43:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}