package com.deodio.elearning.persistence.model;

import java.util.Date;

public class QuizSubjectRel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.quiz_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String quizId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.quiz_subject_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String quizSubjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.account_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.create_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.create_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.update_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.update_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.quiz_subject_order
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private Integer quizSubjectOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject_rel.is_required
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	private Integer isRequired;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.id
	 * @return  the value of t_quiz_subject_rel.id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.id
	 * @param id  the value for t_quiz_subject_rel.id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.quiz_id
	 * @return  the value of t_quiz_subject_rel.quiz_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getQuizId() {
		return quizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.quiz_id
	 * @param quizId  the value for t_quiz_subject_rel.quiz_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setQuizId(String quizId) {
		this.quizId = quizId == null ? null : quizId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.quiz_subject_id
	 * @return  the value of t_quiz_subject_rel.quiz_subject_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getQuizSubjectId() {
		return quizSubjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.quiz_subject_id
	 * @param quizSubjectId  the value for t_quiz_subject_rel.quiz_subject_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setQuizSubjectId(String quizSubjectId) {
		this.quizSubjectId = quizSubjectId == null ? null
				: quizSubjectId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.account_id
	 * @return  the value of t_quiz_subject_rel.account_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.account_id
	 * @param accountId  the value for t_quiz_subject_rel.account_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.create_time
	 * @return  the value of t_quiz_subject_rel.create_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.create_time
	 * @param createTime  the value for t_quiz_subject_rel.create_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.create_id
	 * @return  the value of t_quiz_subject_rel.create_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.create_id
	 * @param createId  the value for t_quiz_subject_rel.create_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.update_time
	 * @return  the value of t_quiz_subject_rel.update_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.update_time
	 * @param updateTime  the value for t_quiz_subject_rel.update_time
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.update_id
	 * @return  the value of t_quiz_subject_rel.update_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.update_id
	 * @param updateId  the value for t_quiz_subject_rel.update_id
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.quiz_subject_order
	 * @return  the value of t_quiz_subject_rel.quiz_subject_order
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public Integer getQuizSubjectOrder() {
		return quizSubjectOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.quiz_subject_order
	 * @param quizSubjectOrder  the value for t_quiz_subject_rel.quiz_subject_order
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setQuizSubjectOrder(Integer quizSubjectOrder) {
		this.quizSubjectOrder = quizSubjectOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject_rel.is_required
	 * @return  the value of t_quiz_subject_rel.is_required
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public Integer getIsRequired() {
		return isRequired;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject_rel.is_required
	 * @param isRequired  the value for t_quiz_subject_rel.is_required
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	public void setIsRequired(Integer isRequired) {
		this.isRequired = isRequired;
	}
}