package com.deodio.elearning.persistence.model;

import java.util.Date;

public class QuizExminationAnswer {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.quiz_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String quizId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.subject_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String subjectId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.subject_opstions_answer
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String subjectOpstionsAnswer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.create_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.create_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.update_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.update_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_exmination_answer.subject_type
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	private Integer subjectType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.id
	 * @return  the value of t_quiz_exmination_answer.id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.id
	 * @param id  the value for t_quiz_exmination_answer.id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.quiz_id
	 * @return  the value of t_quiz_exmination_answer.quiz_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getQuizId() {
		return quizId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.quiz_id
	 * @param quizId  the value for t_quiz_exmination_answer.quiz_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setQuizId(String quizId) {
		this.quizId = quizId == null ? null : quizId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.subject_id
	 * @return  the value of t_quiz_exmination_answer.subject_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getSubjectId() {
		return subjectId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.subject_id
	 * @param subjectId  the value for t_quiz_exmination_answer.subject_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setSubjectId(String subjectId) {
		this.subjectId = subjectId == null ? null : subjectId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.subject_opstions_answer
	 * @return  the value of t_quiz_exmination_answer.subject_opstions_answer
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getSubjectOpstionsAnswer() {
		return subjectOpstionsAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.subject_opstions_answer
	 * @param subjectOpstionsAnswer  the value for t_quiz_exmination_answer.subject_opstions_answer
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setSubjectOpstionsAnswer(String subjectOpstionsAnswer) {
		this.subjectOpstionsAnswer = subjectOpstionsAnswer == null ? null
				: subjectOpstionsAnswer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.create_id
	 * @return  the value of t_quiz_exmination_answer.create_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.create_id
	 * @param createId  the value for t_quiz_exmination_answer.create_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.create_time
	 * @return  the value of t_quiz_exmination_answer.create_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.create_time
	 * @param createTime  the value for t_quiz_exmination_answer.create_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.update_id
	 * @return  the value of t_quiz_exmination_answer.update_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.update_id
	 * @param updateId  the value for t_quiz_exmination_answer.update_id
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.update_time
	 * @return  the value of t_quiz_exmination_answer.update_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.update_time
	 * @param updateTime  the value for t_quiz_exmination_answer.update_time
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_exmination_answer.subject_type
	 * @return  the value of t_quiz_exmination_answer.subject_type
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public Integer getSubjectType() {
		return subjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_exmination_answer.subject_type
	 * @param subjectType  the value for t_quiz_exmination_answer.subject_type
	 * @mbggenerated  Mon Jun 13 11:12:48 CST 2016
	 */
	public void setSubjectType(Integer subjectType) {
		this.subjectType = subjectType;
	}
}