package com.deodio.elearning.persistence.model;

import java.util.Date;

public class QuizSubject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_name
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String quizSubjectName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.create_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.create_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.update_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.update_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.account_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_type
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_bank_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private String quizBankId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_level
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_score
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_expire_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Date quizSubjectExpireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_visible
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectVisible;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_from
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_quiz_subject.quiz_subject_is_publish
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	private Integer quizSubjectIsPublish;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.id
	 * @return  the value of t_quiz_subject.id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.id
	 * @param id  the value for t_quiz_subject.id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_name
	 * @return  the value of t_quiz_subject.quiz_subject_name
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getQuizSubjectName() {
		return quizSubjectName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_name
	 * @param quizSubjectName  the value for t_quiz_subject.quiz_subject_name
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectName(String quizSubjectName) {
		this.quizSubjectName = quizSubjectName == null ? null : quizSubjectName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.create_time
	 * @return  the value of t_quiz_subject.create_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.create_time
	 * @param createTime  the value for t_quiz_subject.create_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.create_id
	 * @return  the value of t_quiz_subject.create_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.create_id
	 * @param createId  the value for t_quiz_subject.create_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.update_time
	 * @return  the value of t_quiz_subject.update_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.update_time
	 * @param updateTime  the value for t_quiz_subject.update_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.update_id
	 * @return  the value of t_quiz_subject.update_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.update_id
	 * @param updateId  the value for t_quiz_subject.update_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.account_id
	 * @return  the value of t_quiz_subject.account_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.account_id
	 * @param accountId  the value for t_quiz_subject.account_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_type
	 * @return  the value of t_quiz_subject.quiz_subject_type
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectType() {
		return quizSubjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_type
	 * @param quizSubjectType  the value for t_quiz_subject.quiz_subject_type
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectType(Integer quizSubjectType) {
		this.quizSubjectType = quizSubjectType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_bank_id
	 * @return  the value of t_quiz_subject.quiz_bank_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public String getQuizBankId() {
		return quizBankId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_bank_id
	 * @param quizBankId  the value for t_quiz_subject.quiz_bank_id
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizBankId(String quizBankId) {
		this.quizBankId = quizBankId == null ? null : quizBankId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_level
	 * @return  the value of t_quiz_subject.quiz_subject_level
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectLevel() {
		return quizSubjectLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_level
	 * @param quizSubjectLevel  the value for t_quiz_subject.quiz_subject_level
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectLevel(Integer quizSubjectLevel) {
		this.quizSubjectLevel = quizSubjectLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_score
	 * @return  the value of t_quiz_subject.quiz_subject_score
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectScore() {
		return quizSubjectScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_score
	 * @param quizSubjectScore  the value for t_quiz_subject.quiz_subject_score
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectScore(Integer quizSubjectScore) {
		this.quizSubjectScore = quizSubjectScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_expire_time
	 * @return  the value of t_quiz_subject.quiz_subject_expire_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Date getQuizSubjectExpireTime() {
		return quizSubjectExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_expire_time
	 * @param quizSubjectExpireTime  the value for t_quiz_subject.quiz_subject_expire_time
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectExpireTime(Date quizSubjectExpireTime) {
		this.quizSubjectExpireTime = quizSubjectExpireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_visible
	 * @return  the value of t_quiz_subject.quiz_subject_visible
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectVisible() {
		return quizSubjectVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_visible
	 * @param quizSubjectVisible  the value for t_quiz_subject.quiz_subject_visible
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectVisible(Integer quizSubjectVisible) {
		this.quizSubjectVisible = quizSubjectVisible;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_from
	 * @return  the value of t_quiz_subject.quiz_subject_from
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectFrom() {
		return quizSubjectFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_from
	 * @param quizSubjectFrom  the value for t_quiz_subject.quiz_subject_from
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectFrom(Integer quizSubjectFrom) {
		this.quizSubjectFrom = quizSubjectFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_quiz_subject.quiz_subject_is_publish
	 * @return  the value of t_quiz_subject.quiz_subject_is_publish
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public Integer getQuizSubjectIsPublish() {
		return quizSubjectIsPublish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_quiz_subject.quiz_subject_is_publish
	 * @param quizSubjectIsPublish  the value for t_quiz_subject.quiz_subject_is_publish
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	public void setQuizSubjectIsPublish(Integer quizSubjectIsPublish) {
		this.quizSubjectIsPublish = quizSubjectIsPublish;
	}
}