package com.deodio.elearning.persistence.model;

import java.util.Date;

public class ServicePlanCmobo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.cmobo_type
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private Integer cmoboType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.cmobo_desc
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String cmoboDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.cmobo_identifier
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String cmoboIdentifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.create_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.create_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.update_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.update_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_service_plan_cmobo.version
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.id
     *
     * @return the value of sys_service_plan_cmobo.id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.id
     *
     * @param id the value for sys_service_plan_cmobo.id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.cmobo_type
     *
     * @return the value of sys_service_plan_cmobo.cmobo_type
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public Integer getCmoboType() {
        return cmoboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.cmobo_type
     *
     * @param cmoboType the value for sys_service_plan_cmobo.cmobo_type
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setCmoboType(Integer cmoboType) {
        this.cmoboType = cmoboType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.cmobo_desc
     *
     * @return the value of sys_service_plan_cmobo.cmobo_desc
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getCmoboDesc() {
        return cmoboDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.cmobo_desc
     *
     * @param cmoboDesc the value for sys_service_plan_cmobo.cmobo_desc
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setCmoboDesc(String cmoboDesc) {
        this.cmoboDesc = cmoboDesc == null ? null : cmoboDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.cmobo_identifier
     *
     * @return the value of sys_service_plan_cmobo.cmobo_identifier
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getCmoboIdentifier() {
        return cmoboIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.cmobo_identifier
     *
     * @param cmoboIdentifier the value for sys_service_plan_cmobo.cmobo_identifier
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setCmoboIdentifier(String cmoboIdentifier) {
        this.cmoboIdentifier = cmoboIdentifier == null ? null : cmoboIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.create_id
     *
     * @return the value of sys_service_plan_cmobo.create_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.create_id
     *
     * @param createId the value for sys_service_plan_cmobo.create_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setCreateId(String createId) {
        this.createId = createId == null ? null : createId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.create_time
     *
     * @return the value of sys_service_plan_cmobo.create_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.create_time
     *
     * @param createTime the value for sys_service_plan_cmobo.create_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.update_id
     *
     * @return the value of sys_service_plan_cmobo.update_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.update_id
     *
     * @param updateId the value for sys_service_plan_cmobo.update_id
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setUpdateId(String updateId) {
        this.updateId = updateId == null ? null : updateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.update_time
     *
     * @return the value of sys_service_plan_cmobo.update_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.update_time
     *
     * @param updateTime the value for sys_service_plan_cmobo.update_time
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_service_plan_cmobo.version
     *
     * @return the value of sys_service_plan_cmobo.version
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_service_plan_cmobo.version
     *
     * @param version the value for sys_service_plan_cmobo.version
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }
}