package com.deodio.elearning.persistence.model;

import java.util.Date;

public class Survey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.survey_name
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String surveyName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.survey_desc
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String surveyDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.create_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.create_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.update_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.update_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.account_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String accountId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.start_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.end_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.is_publish
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Integer isPublish;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.survey_model
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Integer surveyModel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.authority_user_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String authorityUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.authority_user_is_edit
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private Integer authorityUserIsEdit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.survey_cover
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String surveyCover;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.attach_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String attachId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_survey.group_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	private String groupId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.id
	 * @return  the value of t_survey.id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.id
	 * @param id  the value for t_survey.id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.survey_name
	 * @return  the value of t_survey.survey_name
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getSurveyName() {
		return surveyName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.survey_name
	 * @param surveyName  the value for t_survey.survey_name
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setSurveyName(String surveyName) {
		this.surveyName = surveyName == null ? null : surveyName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.survey_desc
	 * @return  the value of t_survey.survey_desc
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getSurveyDesc() {
		return surveyDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.survey_desc
	 * @param surveyDesc  the value for t_survey.survey_desc
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setSurveyDesc(String surveyDesc) {
		this.surveyDesc = surveyDesc == null ? null : surveyDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.create_id
	 * @return  the value of t_survey.create_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.create_id
	 * @param createId  the value for t_survey.create_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.create_time
	 * @return  the value of t_survey.create_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.create_time
	 * @param createTime  the value for t_survey.create_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.update_id
	 * @return  the value of t_survey.update_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.update_id
	 * @param updateId  the value for t_survey.update_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.update_time
	 * @return  the value of t_survey.update_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.update_time
	 * @param updateTime  the value for t_survey.update_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.account_id
	 * @return  the value of t_survey.account_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.account_id
	 * @param accountId  the value for t_survey.account_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.start_time
	 * @return  the value of t_survey.start_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.start_time
	 * @param startTime  the value for t_survey.start_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.end_time
	 * @return  the value of t_survey.end_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.end_time
	 * @param endTime  the value for t_survey.end_time
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.is_publish
	 * @return  the value of t_survey.is_publish
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Integer getIsPublish() {
		return isPublish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.is_publish
	 * @param isPublish  the value for t_survey.is_publish
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setIsPublish(Integer isPublish) {
		this.isPublish = isPublish;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.survey_model
	 * @return  the value of t_survey.survey_model
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Integer getSurveyModel() {
		return surveyModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.survey_model
	 * @param surveyModel  the value for t_survey.survey_model
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setSurveyModel(Integer surveyModel) {
		this.surveyModel = surveyModel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.authority_user_id
	 * @return  the value of t_survey.authority_user_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getAuthorityUserId() {
		return authorityUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.authority_user_id
	 * @param authorityUserId  the value for t_survey.authority_user_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setAuthorityUserId(String authorityUserId) {
		this.authorityUserId = authorityUserId == null ? null : authorityUserId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.authority_user_is_edit
	 * @return  the value of t_survey.authority_user_is_edit
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public Integer getAuthorityUserIsEdit() {
		return authorityUserIsEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.authority_user_is_edit
	 * @param authorityUserIsEdit  the value for t_survey.authority_user_is_edit
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setAuthorityUserIsEdit(Integer authorityUserIsEdit) {
		this.authorityUserIsEdit = authorityUserIsEdit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.survey_cover
	 * @return  the value of t_survey.survey_cover
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getSurveyCover() {
		return surveyCover;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.survey_cover
	 * @param surveyCover  the value for t_survey.survey_cover
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setSurveyCover(String surveyCover) {
		this.surveyCover = surveyCover == null ? null : surveyCover.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.attach_id
	 * @return  the value of t_survey.attach_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getAttachId() {
		return attachId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.attach_id
	 * @param attachId  the value for t_survey.attach_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setAttachId(String attachId) {
		this.attachId = attachId == null ? null : attachId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_survey.group_id
	 * @return  the value of t_survey.group_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_survey.group_id
	 * @param groupId  the value for t_survey.group_id
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId == null ? null : groupId.trim();
	}
}