package com.deodio.elearning.persistence.model;

import java.util.Date;

public class Trainers {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_name
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_desc
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_gender
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Integer trainerGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_type
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Integer trainerType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_title
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_mobile_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerMobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_desk_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerDeskPhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_mail
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerMail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_level
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Integer trainerLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_organization
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerOrganization;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.is_recommended
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Integer isRecommended;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.create_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String createId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.create_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.update_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String updateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.update_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.trainer_portrait_url
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String trainerPortraitUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_trainers.account_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	private String accountId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.id
	 * @return  the value of t_trainers.id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.id
	 * @param id  the value for t_trainers.id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_name
	 * @return  the value of t_trainers.trainer_name
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerName() {
		return trainerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_name
	 * @param trainerName  the value for t_trainers.trainer_name
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerName(String trainerName) {
		this.trainerName = trainerName == null ? null : trainerName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_desc
	 * @return  the value of t_trainers.trainer_desc
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerDesc() {
		return trainerDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_desc
	 * @param trainerDesc  the value for t_trainers.trainer_desc
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerDesc(String trainerDesc) {
		this.trainerDesc = trainerDesc == null ? null : trainerDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_gender
	 * @return  the value of t_trainers.trainer_gender
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Integer getTrainerGender() {
		return trainerGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_gender
	 * @param trainerGender  the value for t_trainers.trainer_gender
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerGender(Integer trainerGender) {
		this.trainerGender = trainerGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_type
	 * @return  the value of t_trainers.trainer_type
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Integer getTrainerType() {
		return trainerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_type
	 * @param trainerType  the value for t_trainers.trainer_type
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerType(Integer trainerType) {
		this.trainerType = trainerType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_title
	 * @return  the value of t_trainers.trainer_title
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerTitle() {
		return trainerTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_title
	 * @param trainerTitle  the value for t_trainers.trainer_title
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerTitle(String trainerTitle) {
		this.trainerTitle = trainerTitle == null ? null : trainerTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_mobile_phone
	 * @return  the value of t_trainers.trainer_mobile_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerMobilePhone() {
		return trainerMobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_mobile_phone
	 * @param trainerMobilePhone  the value for t_trainers.trainer_mobile_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerMobilePhone(String trainerMobilePhone) {
		this.trainerMobilePhone = trainerMobilePhone == null ? null
				: trainerMobilePhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_desk_phone
	 * @return  the value of t_trainers.trainer_desk_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerDeskPhone() {
		return trainerDeskPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_desk_phone
	 * @param trainerDeskPhone  the value for t_trainers.trainer_desk_phone
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerDeskPhone(String trainerDeskPhone) {
		this.trainerDeskPhone = trainerDeskPhone == null ? null
				: trainerDeskPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_mail
	 * @return  the value of t_trainers.trainer_mail
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerMail() {
		return trainerMail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_mail
	 * @param trainerMail  the value for t_trainers.trainer_mail
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerMail(String trainerMail) {
		this.trainerMail = trainerMail == null ? null : trainerMail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_level
	 * @return  the value of t_trainers.trainer_level
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Integer getTrainerLevel() {
		return trainerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_level
	 * @param trainerLevel  the value for t_trainers.trainer_level
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerLevel(Integer trainerLevel) {
		this.trainerLevel = trainerLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_organization
	 * @return  the value of t_trainers.trainer_organization
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerOrganization() {
		return trainerOrganization;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_organization
	 * @param trainerOrganization  the value for t_trainers.trainer_organization
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerOrganization(String trainerOrganization) {
		this.trainerOrganization = trainerOrganization == null ? null
				: trainerOrganization.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.is_recommended
	 * @return  the value of t_trainers.is_recommended
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Integer getIsRecommended() {
		return isRecommended;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.is_recommended
	 * @param isRecommended  the value for t_trainers.is_recommended
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setIsRecommended(Integer isRecommended) {
		this.isRecommended = isRecommended;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.create_id
	 * @return  the value of t_trainers.create_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.create_id
	 * @param createId  the value for t_trainers.create_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setCreateId(String createId) {
		this.createId = createId == null ? null : createId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.create_time
	 * @return  the value of t_trainers.create_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.create_time
	 * @param createTime  the value for t_trainers.create_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.update_id
	 * @return  the value of t_trainers.update_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getUpdateId() {
		return updateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.update_id
	 * @param updateId  the value for t_trainers.update_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setUpdateId(String updateId) {
		this.updateId = updateId == null ? null : updateId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.update_time
	 * @return  the value of t_trainers.update_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.update_time
	 * @param updateTime  the value for t_trainers.update_time
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.trainer_portrait_url
	 * @return  the value of t_trainers.trainer_portrait_url
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getTrainerPortraitUrl() {
		return trainerPortraitUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.trainer_portrait_url
	 * @param trainerPortraitUrl  the value for t_trainers.trainer_portrait_url
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setTrainerPortraitUrl(String trainerPortraitUrl) {
		this.trainerPortraitUrl = trainerPortraitUrl == null ? null
				: trainerPortraitUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_trainers.account_id
	 * @return  the value of t_trainers.account_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public String getAccountId() {
		return accountId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_trainers.account_id
	 * @param accountId  the value for t_trainers.account_id
	 * @mbggenerated  Thu Jun 02 16:35:13 CST 2016
	 */
	public void setAccountId(String accountId) {
		this.accountId = accountId == null ? null : accountId.trim();
	}
}