package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AccountItemsRel;
import com.deodio.elearning.persistence.model.AccountItemsRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountItemsRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int countByExample(AccountItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int deleteByExample(AccountItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int insert(AccountItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int insertSelective(AccountItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	List<AccountItemsRel> selectByExample(AccountItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	AccountItemsRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AccountItemsRel record,
			@Param("example") AccountItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByExample(@Param("record") AccountItemsRel record, @Param("example") AccountItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByPrimaryKeySelective(AccountItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_items_rel
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByPrimaryKey(AccountItemsRel record);
}