package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AccountPreferential;
import com.deodio.elearning.persistence.model.AccountPreferentialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountPreferentialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int countByExample(AccountPreferentialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int deleteByExample(AccountPreferentialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int insert(AccountPreferential record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int insertSelective(AccountPreferential record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	List<AccountPreferential> selectByExample(AccountPreferentialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	AccountPreferential selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AccountPreferential record,
			@Param("example") AccountPreferentialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByExample(@Param("record") AccountPreferential record,
			@Param("example") AccountPreferentialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByPrimaryKeySelective(AccountPreferential record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_preferential
	 * @mbggenerated  Tue Nov 22 15:49:56 CST 2016
	 */
	int updateByPrimaryKey(AccountPreferential record);
}