package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AccountCapability;
import com.deodio.elearning.persistence.model.AccountCapabilityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountCapabilityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int countByExample(AccountCapabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int deleteByExample(AccountCapabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int insert(AccountCapability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int insertSelective(AccountCapability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    List<AccountCapability> selectByExample(AccountCapabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    AccountCapability selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") AccountCapability record, @Param("example") AccountCapabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int updateByExample(@Param("record") AccountCapability record, @Param("example") AccountCapabilityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int updateByPrimaryKeySelective(AccountCapability record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_capability
     *
     * @mbggenerated Sun Aug 28 16:36:35 CST 2016
     */
    int updateByPrimaryKey(AccountCapability record);
}