package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AccountClassificationRel;
import com.deodio.elearning.persistence.model.AccountClassificationRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountClassificationRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int countByExample(AccountClassificationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int deleteByExample(AccountClassificationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int insert(AccountClassificationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int insertSelective(AccountClassificationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    List<AccountClassificationRel> selectByExample(AccountClassificationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    AccountClassificationRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") AccountClassificationRel record, @Param("example") AccountClassificationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int updateByExample(@Param("record") AccountClassificationRel record, @Param("example") AccountClassificationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int updateByPrimaryKeySelective(AccountClassificationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account_classification_rel
     *
     * @mbggenerated Wed Feb 08 17:30:51 CST 2017
     */
    int updateByPrimaryKey(AccountClassificationRel record);
}