package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AccountAttachment;
import com.deodio.elearning.persistence.model.AccountAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountAttachmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int countByExample(AccountAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int deleteByExample(AccountAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int insert(AccountAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int insertSelective(AccountAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	List<AccountAttachment> selectByExample(AccountAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	AccountAttachment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int updateByExampleSelective(@Param("record") AccountAttachment record,
			@Param("example") AccountAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int updateByExample(@Param("record") AccountAttachment record,
			@Param("example") AccountAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int updateByPrimaryKeySelective(AccountAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_account_attachment
	 * @mbggenerated  Sun Aug 28 14:52:37 CST 2016
	 */
	int updateByPrimaryKey(AccountAttachment record);
}