package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AttachmentScromItem;
import com.deodio.elearning.persistence.model.AttachmentScromItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentScromItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int countByExample(AttachmentScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int deleteByExample(AttachmentScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int insert(AttachmentScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int insertSelective(AttachmentScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	List<AttachmentScromItem> selectByExample(AttachmentScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	AttachmentScromItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AttachmentScromItem record,
			@Param("example") AttachmentScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int updateByExample(@Param("record") AttachmentScromItem record,
			@Param("example") AttachmentScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int updateByPrimaryKeySelective(AttachmentScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_scrom_item
	 * @mbggenerated  Mon Feb 27 11:33:12 CST 2017
	 */
	int updateByPrimaryKey(AttachmentScromItem record);
}