package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.AttachmentItemsRel;
import com.deodio.elearning.persistence.model.AttachmentItemsRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentItemsRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int countByExample(AttachmentItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int deleteByExample(AttachmentItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int insert(AttachmentItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int insertSelective(AttachmentItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	List<AttachmentItemsRel> selectByExample(AttachmentItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	AttachmentItemsRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int updateByExampleSelective(@Param("record") AttachmentItemsRel record,
			@Param("example") AttachmentItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int updateByExample(@Param("record") AttachmentItemsRel record,
			@Param("example") AttachmentItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int updateByPrimaryKeySelective(AttachmentItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment_items_rel
	 * @mbggenerated  Fri Feb 24 10:37:51 CST 2017
	 */
	int updateByPrimaryKey(AttachmentItemsRel record);
}