package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.Attachment;
import com.deodio.elearning.persistence.model.AttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttachmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int countByExample(AttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int deleteByExample(AttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int insert(Attachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int insertSelective(Attachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	List<Attachment> selectByExample(AttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	Attachment selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Attachment record, @Param("example") AttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int updateByExample(@Param("record") Attachment record, @Param("example") AttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int updateByPrimaryKeySelective(Attachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_attachment
	 * @mbggenerated  Tue Mar 07 16:52:29 CST 2017
	 */
	int updateByPrimaryKey(Attachment record);
}