package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.Classification;
import com.deodio.elearning.persistence.model.ClassificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassificationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int countByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int deleteByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int insert(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int insertSelective(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	List<Classification> selectByExample(ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	Classification selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Classification record,
			@Param("example") ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int updateByExample(@Param("record") Classification record,
			@Param("example") ClassificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int updateByPrimaryKeySelective(Classification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_classification
	 * @mbggenerated  Thu Jun 16 13:42:58 CST 2016
	 */
	int updateByPrimaryKey(Classification record);
}