package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseModelOnline;
import com.deodio.elearning.persistence.model.CourseModelOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseModelOnlineMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	long countByExample(CourseModelOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int deleteByExample(CourseModelOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int insert(CourseModelOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int insertSelective(CourseModelOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	List<CourseModelOnline> selectByExample(CourseModelOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	CourseModelOnline selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CourseModelOnline record,
			@Param("example") CourseModelOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int updateByExample(@Param("record") CourseModelOnline record, @Param("example") CourseModelOnlineExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int updateByPrimaryKeySelective(CourseModelOnline record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_model_online
	 * @mbg.generated  Tue Aug 21 14:47:46 CST 2018
	 */
	int updateByPrimaryKey(CourseModelOnline record);
}