package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseRegisteRule;
import com.deodio.elearning.persistence.model.CourseRegisteRuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseRegisteRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int countByExample(CourseRegisteRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int deleteByExample(CourseRegisteRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int insert(CourseRegisteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int insertSelective(CourseRegisteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    List<CourseRegisteRule> selectByExample(CourseRegisteRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    CourseRegisteRule selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int updateByExampleSelective(@Param("record") CourseRegisteRule record, @Param("example") CourseRegisteRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int updateByExample(@Param("record") CourseRegisteRule record, @Param("example") CourseRegisteRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int updateByPrimaryKeySelective(CourseRegisteRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_registe_rule
     *
     * @mbggenerated Wed Oct 26 13:17:02 CST 2016
     */
    int updateByPrimaryKey(CourseRegisteRule record);
}