package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseMaterial;
import com.deodio.elearning.persistence.model.CourseMaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseMaterialMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int countByExample(CourseMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int deleteByExample(CourseMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int insert(CourseMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int insertSelective(CourseMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	List<CourseMaterial> selectByExample(CourseMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	CourseMaterial selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CourseMaterial record,
			@Param("example") CourseMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int updateByExample(@Param("record") CourseMaterial record, @Param("example") CourseMaterialExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int updateByPrimaryKeySelective(CourseMaterial record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_material
	 * @mbggenerated  Fri Sep 30 15:24:29 CST 2016
	 */
	int updateByPrimaryKey(CourseMaterial record);
}