package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseTrainee;
import com.deodio.elearning.persistence.model.CourseTraineeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseTraineeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int countByExample(CourseTraineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int deleteByExample(CourseTraineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int insert(CourseTrainee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int insertSelective(CourseTrainee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    List<CourseTrainee> selectByExample(CourseTraineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    CourseTrainee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int updateByExampleSelective(@Param("record") CourseTrainee record, @Param("example") CourseTraineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int updateByExample(@Param("record") CourseTrainee record, @Param("example") CourseTraineeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int updateByPrimaryKeySelective(CourseTrainee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course
     *
     * @mbggenerated Fri Jun 16 17:10:56 CST 2017
     */
    int updateByPrimaryKey(CourseTrainee record);
}