package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseUserRel;
import com.deodio.elearning.persistence.model.CourseUserRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseUserRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int countByExample(CourseUserRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int deleteByExample(CourseUserRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int insert(CourseUserRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int insertSelective(CourseUserRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	List<CourseUserRel> selectByExample(CourseUserRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	CourseUserRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CourseUserRel record, @Param("example") CourseUserRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int updateByExample(@Param("record") CourseUserRel record, @Param("example") CourseUserRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int updateByPrimaryKeySelective(CourseUserRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_user_rel
	 * @mbggenerated  Wed Aug 29 10:45:13 CST 2018
	 */
	int updateByPrimaryKey(CourseUserRel record);
}