package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseNotice;
import com.deodio.elearning.persistence.model.CourseNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseNoticeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int countByExample(CourseNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int deleteByExample(CourseNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int insert(CourseNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int insertSelective(CourseNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	List<CourseNotice> selectByExample(CourseNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	CourseNotice selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") CourseNotice record, @Param("example") CourseNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int updateByExample(@Param("record") CourseNotice record, @Param("example") CourseNoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int updateByPrimaryKeySelective(CourseNotice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_course_notice
	 * @mbggenerated  Thu Sep 29 17:45:16 CST 2016
	 */
	int updateByPrimaryKey(CourseNotice record);
}