package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.CourseSurvey;
import com.deodio.elearning.persistence.model.CourseSurveyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CourseSurveyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int countByExample(CourseSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int deleteByExample(CourseSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int insert(CourseSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int insertSelective(CourseSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    List<CourseSurvey> selectByExample(CourseSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    CourseSurvey selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int updateByExampleSelective(@Param("record") CourseSurvey record, @Param("example") CourseSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int updateByExample(@Param("record") CourseSurvey record, @Param("example") CourseSurveyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int updateByPrimaryKeySelective(CourseSurvey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_survey
     *
     * @mbggenerated Sun Oct 09 13:21:17 CST 2016
     */
    int updateByPrimaryKey(CourseSurvey record);

	void delAllCourseSurveyByCourseId(Map<String, Object> params);
}