package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.DiscussionModel;
import com.deodio.elearning.persistence.model.DiscussionModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscussionModelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int countByExample(DiscussionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int deleteByExample(DiscussionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int insert(DiscussionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int insertSelective(DiscussionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	List<DiscussionModel> selectByExample(DiscussionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	DiscussionModel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DiscussionModel record,
			@Param("example") DiscussionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int updateByExample(@Param("record") DiscussionModel record, @Param("example") DiscussionModelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int updateByPrimaryKeySelective(DiscussionModel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_discussion
	 * @mbggenerated  Mon Jul 24 16:38:19 CST 2017
	 */
	int updateByPrimaryKey(DiscussionModel record);
}