package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.GroupItems;
import com.deodio.elearning.persistence.model.GroupItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int countByExample(GroupItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int deleteByExample(GroupItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int insert(GroupItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int insertSelective(GroupItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    List<GroupItems> selectByExample(GroupItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    GroupItems selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupItems record, @Param("example") GroupItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int updateByExample(@Param("record") GroupItems record, @Param("example") GroupItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int updateByPrimaryKeySelective(GroupItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_items
     *
     * @mbggenerated Tue Sep 20 18:52:06 CST 2016
     */
    int updateByPrimaryKey(GroupItems record);
}