package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.GroupCourse;
import com.deodio.elearning.persistence.model.GroupCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int countByExample(GroupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int deleteByExample(GroupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int insert(GroupCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int insertSelective(GroupCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    List<GroupCourse> selectByExample(GroupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    GroupCourse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int updateByExampleSelective(@Param("record") GroupCourse record, @Param("example") GroupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int updateByExample(@Param("record") GroupCourse record, @Param("example") GroupCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int updateByPrimaryKeySelective(GroupCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_course
     *
     * @mbggenerated Thu Jun 14 17:43:21 CST 2018
     */
    int updateByPrimaryKey(GroupCourse record);
}