package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.GroupSurvey;
import com.deodio.elearning.persistence.model.GroupSurveyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupSurveyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int countByExample(GroupSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int deleteByExample(GroupSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int insert(GroupSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int insertSelective(GroupSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	List<GroupSurvey> selectByExample(GroupSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	GroupSurvey selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int updateByExampleSelective(@Param("record") GroupSurvey record,
			@Param("example") GroupSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int updateByExample(@Param("record") GroupSurvey record,
			@Param("example") GroupSurveyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int updateByPrimaryKeySelective(GroupSurvey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_group_survey
	 * @mbggenerated  Wed Apr 27 11:03:16 CST 2016
	 */
	int updateByPrimaryKey(GroupSurvey record);
}