package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.GroupFunction;
import com.deodio.elearning.persistence.model.GroupFunctionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int countByExample(GroupFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int deleteByExample(GroupFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int insert(GroupFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int insertSelective(GroupFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    List<GroupFunction> selectByExample(GroupFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    GroupFunction selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int updateByExampleSelective(@Param("record") GroupFunction record, @Param("example") GroupFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int updateByExample(@Param("record") GroupFunction record, @Param("example") GroupFunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int updateByPrimaryKeySelective(GroupFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_group_function
     *
     * @mbggenerated Fri Mar 25 11:02:57 CST 2016
     */
    int updateByPrimaryKey(GroupFunction record);
}