package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.KnowledgePoints;
import com.deodio.elearning.persistence.model.KnowledgePointsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowledgePointsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int countByExample(KnowledgePointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int deleteByExample(KnowledgePointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int insert(KnowledgePoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int insertSelective(KnowledgePoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	List<KnowledgePoints> selectByExample(KnowledgePointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	KnowledgePoints selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int updateByExampleSelective(@Param("record") KnowledgePoints record,
			@Param("example") KnowledgePointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int updateByExample(@Param("record") KnowledgePoints record,
			@Param("example") KnowledgePointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int updateByPrimaryKeySelective(KnowledgePoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_knowledge_points
	 * @mbggenerated  Sun Sep 25 16:34:08 CST 2016
	 */
	int updateByPrimaryKey(KnowledgePoints record);
}