package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.Locations;
import com.deodio.elearning.persistence.model.LocationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int countByExample(LocationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int deleteByExample(LocationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int insert(Locations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int insertSelective(Locations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	List<Locations> selectByExample(LocationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	Locations selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Locations record, @Param("example") LocationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int updateByExample(@Param("record") Locations record, @Param("example") LocationsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int updateByPrimaryKeySelective(Locations record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_locations
	 * @mbggenerated  Tue Jun 21 11:07:06 CST 2016
	 */
	int updateByPrimaryKey(Locations record);
}