package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationSyncSlides;
import com.deodio.elearning.persistence.model.PresentationSyncSlidesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationSyncSlidesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int countByExample(PresentationSyncSlidesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int deleteByExample(PresentationSyncSlidesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int insert(PresentationSyncSlides record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int insertSelective(PresentationSyncSlides record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	List<PresentationSyncSlides> selectByExample(
			PresentationSyncSlidesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	PresentationSyncSlides selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int updateByExampleSelective(
			@Param("record") PresentationSyncSlides record,
			@Param("example") PresentationSyncSlidesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int updateByExample(@Param("record") PresentationSyncSlides record,
			@Param("example") PresentationSyncSlidesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int updateByPrimaryKeySelective(PresentationSyncSlides record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_slides
	 * @mbggenerated  Tue May 17 09:47:23 CST 2016
	 */
	int updateByPrimaryKey(PresentationSyncSlides record);
}