package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationFiles;
import com.deodio.elearning.persistence.model.PresentationFilesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationFilesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int countByExample(PresentationFilesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int deleteByExample(PresentationFilesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int insert(PresentationFiles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int insertSelective(PresentationFiles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	List<PresentationFiles> selectByExample(PresentationFilesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	PresentationFiles selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int updateByExampleSelective(@Param("record") PresentationFiles record,
			@Param("example") PresentationFilesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int updateByExample(@Param("record") PresentationFiles record,
			@Param("example") PresentationFilesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int updateByPrimaryKeySelective(PresentationFiles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_files
	 * @mbggenerated  Mon Jul 11 11:19:49 CST 2016
	 */
	int updateByPrimaryKey(PresentationFiles record);
}