package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationSyncQuizs;
import com.deodio.elearning.persistence.model.PresentationSyncQuizsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationSyncQuizsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int countByExample(PresentationSyncQuizsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int deleteByExample(PresentationSyncQuizsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int insert(PresentationSyncQuizs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int insertSelective(PresentationSyncQuizs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	List<PresentationSyncQuizs> selectByExample(
			PresentationSyncQuizsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	PresentationSyncQuizs selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int updateByExampleSelective(@Param("record") PresentationSyncQuizs record,
			@Param("example") PresentationSyncQuizsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int updateByExample(@Param("record") PresentationSyncQuizs record,
			@Param("example") PresentationSyncQuizsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int updateByPrimaryKeySelective(PresentationSyncQuizs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_quizs
	 * @mbggenerated  Fri Mar 18 11:10:26 CST 2016
	 */
	int updateByPrimaryKey(PresentationSyncQuizs record);
}