package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationScromItem;
import com.deodio.elearning.persistence.model.PresentationScromItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationScromItemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int countByExample(PresentationScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int deleteByExample(PresentationScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int insert(PresentationScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int insertSelective(PresentationScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	List<PresentationScromItem> selectByExample(
			PresentationScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	PresentationScromItem selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int updateByExampleSelective(@Param("record") PresentationScromItem record,
			@Param("example") PresentationScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int updateByExample(@Param("record") PresentationScromItem record,
			@Param("example") PresentationScromItemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int updateByPrimaryKeySelective(PresentationScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Sun Jul 17 18:21:15 CST 2016
	 */
	int updateByPrimaryKey(PresentationScromItem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_scrom_item
	 * @mbggenerated  Mon Jul 11 15:41:21 CST 2016
	 */

}