package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationDiscussionReply;
import com.deodio.elearning.persistence.model.PresentationDiscussionReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationDiscussionReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int countByExample(PresentationDiscussionReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int deleteByExample(PresentationDiscussionReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int insert(PresentationDiscussionReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int insertSelective(PresentationDiscussionReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	List<PresentationDiscussionReply> selectByExample(PresentationDiscussionReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	PresentationDiscussionReply selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int updateByExampleSelective(@Param("record") PresentationDiscussionReply record,
			@Param("example") PresentationDiscussionReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int updateByExample(@Param("record") PresentationDiscussionReply record,
			@Param("example") PresentationDiscussionReplyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int updateByPrimaryKeySelective(PresentationDiscussionReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_discussion_reply
	 * @mbggenerated  Wed Aug 01 18:39:29 CST 2018
	 */
	int updateByPrimaryKey(PresentationDiscussionReply record);
}