package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationModelScrom;
import com.deodio.elearning.persistence.model.PresentationModelScromExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationModelScromMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int countByExample(PresentationModelScromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int deleteByExample(PresentationModelScromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int insert(PresentationModelScrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int insertSelective(PresentationModelScrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    List<PresentationModelScrom> selectByExample(PresentationModelScromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    PresentationModelScrom selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") PresentationModelScrom record, @Param("example") PresentationModelScromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int updateByExample(@Param("record") PresentationModelScrom record, @Param("example") PresentationModelScromExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int updateByPrimaryKeySelective(PresentationModelScrom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_presentation_model_scrom
     *
     * @mbggenerated Mon Jul 11 14:27:28 CST 2016
     */
    int updateByPrimaryKey(PresentationModelScrom record);
}