package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.PresentationSyncPoints;
import com.deodio.elearning.persistence.model.PresentationSyncPointsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PresentationSyncPointsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int countByExample(PresentationSyncPointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int deleteByExample(PresentationSyncPointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int insert(PresentationSyncPoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int insertSelective(PresentationSyncPoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	List<PresentationSyncPoints> selectByExample(PresentationSyncPointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	PresentationSyncPoints selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int updateByExampleSelective(@Param("record") PresentationSyncPoints record,
			@Param("example") PresentationSyncPointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int updateByExample(@Param("record") PresentationSyncPoints record,
			@Param("example") PresentationSyncPointsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int updateByPrimaryKeySelective(PresentationSyncPoints record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_presentation_sync_points
	 * @mbggenerated  Mon Sep 10 11:26:12 CST 2018
	 */
	int updateByPrimaryKey(PresentationSyncPoints record);
}