package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizSubjectKnowledgeRel;
import com.deodio.elearning.persistence.model.QuizSubjectKnowledgeRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizSubjectKnowledgeRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int countByExample(QuizSubjectKnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int deleteByExample(QuizSubjectKnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int insert(QuizSubjectKnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int insertSelective(QuizSubjectKnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    List<QuizSubjectKnowledgeRel> selectByExample(QuizSubjectKnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    QuizSubjectKnowledgeRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int updateByExampleSelective(@Param("record") QuizSubjectKnowledgeRel record, @Param("example") QuizSubjectKnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int updateByExample(@Param("record") QuizSubjectKnowledgeRel record, @Param("example") QuizSubjectKnowledgeRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int updateByPrimaryKeySelective(QuizSubjectKnowledgeRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_subject_knowledge_rel
     *
     * @mbggenerated Mon May 16 15:52:29 CST 2016
     */
    int updateByPrimaryKey(QuizSubjectKnowledgeRel record);
}