package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizAutoRuleSubject;
import com.deodio.elearning.persistence.model.QuizAutoRuleSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizAutoRuleSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int countByExample(QuizAutoRuleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int deleteByExample(QuizAutoRuleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int insert(QuizAutoRuleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int insertSelective(QuizAutoRuleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    List<QuizAutoRuleSubject> selectByExample(QuizAutoRuleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    QuizAutoRuleSubject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") QuizAutoRuleSubject record, @Param("example") QuizAutoRuleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByExample(@Param("record") QuizAutoRuleSubject record, @Param("example") QuizAutoRuleSubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByPrimaryKeySelective(QuizAutoRuleSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_subject
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByPrimaryKey(QuizAutoRuleSubject record);
}