package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizSubject;
import com.deodio.elearning.persistence.model.QuizSubjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizSubjectMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	long countByExample(QuizSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int deleteByExample(QuizSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int insert(QuizSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int insertSelective(QuizSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	List<QuizSubject> selectByExample(QuizSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	QuizSubject selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int updateByExampleSelective(@Param("record") QuizSubject record, @Param("example") QuizSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int updateByExample(@Param("record") QuizSubject record, @Param("example") QuizSubjectExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int updateByPrimaryKeySelective(QuizSubject record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject
	 * @mbg.generated  Mon Jun 25 15:24:37 CST 2018
	 */
	int updateByPrimaryKey(QuizSubject record);
}