package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizRel;
import com.deodio.elearning.persistence.model.QuizRelExample;
import com.deodio.elearning.persistence.model.QuizRelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int countByExample(QuizRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int deleteByExample(QuizRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int insert(QuizRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int insertSelective(QuizRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	List<QuizRel> selectByExample(QuizRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	QuizRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QuizRel record,
			@Param("example") QuizRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int updateByExample(@Param("record") QuizRel record,
			@Param("example") QuizRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int updateByPrimaryKeySelective(QuizRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_rel
	 * @mbggenerated  Wed Apr 13 14:31:22 CST 2016
	 */
	int updateByPrimaryKey(QuizRel record);
}