package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizAutoRuleBank;
import com.deodio.elearning.persistence.model.QuizAutoRuleBankExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizAutoRuleBankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int countByExample(QuizAutoRuleBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int deleteByExample(QuizAutoRuleBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int insert(QuizAutoRuleBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int insertSelective(QuizAutoRuleBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    List<QuizAutoRuleBank> selectByExample(QuizAutoRuleBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    QuizAutoRuleBank selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") QuizAutoRuleBank record, @Param("example") QuizAutoRuleBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByExample(@Param("record") QuizAutoRuleBank record, @Param("example") QuizAutoRuleBankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByPrimaryKeySelective(QuizAutoRuleBank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_quiz_auto_rule_bank
     *
     * @mbggenerated Fri May 27 14:43:19 CST 2016
     */
    int updateByPrimaryKey(QuizAutoRuleBank record);
}