package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizSubjectRel;
import com.deodio.elearning.persistence.model.QuizSubjectRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizSubjectRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int countByExample(QuizSubjectRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int deleteByExample(QuizSubjectRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int insert(QuizSubjectRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int insertSelective(QuizSubjectRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	List<QuizSubjectRel> selectByExample(QuizSubjectRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	QuizSubjectRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QuizSubjectRel record,
			@Param("example") QuizSubjectRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int updateByExample(@Param("record") QuizSubjectRel record,
			@Param("example") QuizSubjectRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int updateByPrimaryKeySelective(QuizSubjectRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_subject_rel
	 * @mbggenerated  Wed Jun 08 16:14:44 CST 2016
	 */
	int updateByPrimaryKey(QuizSubjectRel record);
}