package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.QuizBanks;
import com.deodio.elearning.persistence.model.QuizBanksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QuizBanksMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int countByExample(QuizBanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int deleteByExample(QuizBanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int insert(QuizBanks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int insertSelective(QuizBanks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	List<QuizBanks> selectByExample(QuizBanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	QuizBanks selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int updateByExampleSelective(@Param("record") QuizBanks record,
			@Param("example") QuizBanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:40 CST 2016
	 */
	int updateByExample(@Param("record") QuizBanks record,
			@Param("example") QuizBanksExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:43 CST 2016
	 */
	int updateByPrimaryKeySelective(QuizBanks record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_quiz_banks
	 * @mbggenerated  Wed May 11 15:49:43 CST 2016
	 */
	int updateByPrimaryKey(QuizBanks record);
}