package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.ServicePlanCmobosRel;
import com.deodio.elearning.persistence.model.ServicePlanCmobosRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServicePlanCmobosRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int countByExample(ServicePlanCmobosRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int deleteByExample(ServicePlanCmobosRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int insert(ServicePlanCmobosRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int insertSelective(ServicePlanCmobosRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    List<ServicePlanCmobosRel> selectByExample(ServicePlanCmobosRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    ServicePlanCmobosRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServicePlanCmobosRel record, @Param("example") ServicePlanCmobosRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByExample(@Param("record") ServicePlanCmobosRel record, @Param("example") ServicePlanCmobosRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByPrimaryKeySelective(ServicePlanCmobosRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan_combos_rel
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByPrimaryKey(ServicePlanCmobosRel record);
}