package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.ServicePlan;
import com.deodio.elearning.persistence.model.ServicePlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServicePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int countByExample(ServicePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int deleteByExample(ServicePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int insert(ServicePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int insertSelective(ServicePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    List<ServicePlan> selectByExample(ServicePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    ServicePlan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByExampleSelective(@Param("record") ServicePlan record, @Param("example") ServicePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByExample(@Param("record") ServicePlan record, @Param("example") ServicePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByPrimaryKeySelective(ServicePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_service_plan
     *
     * @mbggenerated Tue Nov 22 15:49:56 CST 2016
     */
    int updateByPrimaryKey(ServicePlan record);
}