package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.SurveyUserItems;
import com.deodio.elearning.persistence.model.SurveyUserItemsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SurveyUserItemsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int countByExample(SurveyUserItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int deleteByExample(SurveyUserItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int insert(SurveyUserItems record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int insertSelective(SurveyUserItems record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	List<SurveyUserItems> selectByExample(SurveyUserItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") SurveyUserItems record,
			@Param("example") SurveyUserItemsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey_user_items
	 * @mbggenerated  Mon Jun 04 10:03:15 CST 2018
	 */
	int updateByExample(@Param("record") SurveyUserItems record, @Param("example") SurveyUserItemsExample example);
}