package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.Survey;
import com.deodio.elearning.persistence.model.SurveyExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SurveyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int countByExample(SurveyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int deleteByExample(SurveyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int deleteByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int insert(Survey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int insertSelective(Survey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	List<Survey> selectByExample(SurveyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	Survey selectByPrimaryKey(String id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Survey record, @Param("example") SurveyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int updateByExample(@Param("record") Survey record, @Param("example") SurveyExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int updateByPrimaryKeySelective(Survey record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_survey
	 * @mbggenerated  Mon Jul 23 17:59:21 CST 2018
	 */
	int updateByPrimaryKey(Survey record);
	/*获取问卷调查的引用*/
	List<Map<String, Object>> findQuoteSurveyList(Map<String, Object> params);
	/*根据问卷调查的id获取相同账户下的讲师*/
	List<Map<String, Object>> findShareSurveyTrainee(Map<String, Object> params);
	/*设置问卷调查的编辑权限*/
	void setShareSurveyTrainee(Map<String, Object> params);
	/*设置问卷调查是否正在被编辑*/
	void setShareSurveyIsEditNow(Map<String, Object> params);
	Map<String, Object> getSurveyBaseInfo(Map<String, Object> params);
}