package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.SystemTemplate;
import com.deodio.elearning.persistence.model.SystemTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int countByExample(SystemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int deleteByExample(SystemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int insert(SystemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int insertSelective(SystemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	List<SystemTemplate> selectByExample(SystemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	SystemTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int updateByExampleSelective(@Param("record") SystemTemplate record,
			@Param("example") SystemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int updateByExample(@Param("record") SystemTemplate record,
			@Param("example") SystemTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int updateByPrimaryKeySelective(SystemTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_system_template
	 * @mbggenerated  Tue Feb 23 11:15:54 CST 2016
	 */
	int updateByPrimaryKey(SystemTemplate record);
}