package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TagsItemsRel;
import com.deodio.elearning.persistence.model.TagsItemsRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagsItemsRelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int countByExample(TagsItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int deleteByExample(TagsItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int insert(TagsItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int insertSelective(TagsItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	List<TagsItemsRel> selectByExample(TagsItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	TagsItemsRel selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TagsItemsRel record,
			@Param("example") TagsItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int updateByExample(@Param("record") TagsItemsRel record,
			@Param("example") TagsItemsRelExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int updateByPrimaryKeySelective(TagsItemsRel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_tags_items_rel
	 * @mbggenerated  Sat Oct 22 00:55:06 CST 2016
	 */
	int updateByPrimaryKey(TagsItemsRel record);
}