package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TagsPresentationRel;
import com.deodio.elearning.persistence.model.TagsPresentationRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagsPresentationRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int countByExample(TagsPresentationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int deleteByExample(TagsPresentationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int insert(TagsPresentationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int insertSelective(TagsPresentationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    List<TagsPresentationRel> selectByExample(TagsPresentationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    TagsPresentationRel selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") TagsPresentationRel record, @Param("example") TagsPresentationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int updateByExample(@Param("record") TagsPresentationRel record, @Param("example") TagsPresentationRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int updateByPrimaryKeySelective(TagsPresentationRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_tags_presentation_rel
     *
     * @mbggenerated Wed Apr 27 16:33:33 CST 2016
     */
    int updateByPrimaryKey(TagsPresentationRel record);
}