package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TraineeCourse;
import com.deodio.elearning.persistence.model.TraineeCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraineeCourseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int countByExample(TraineeCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int deleteByExample(TraineeCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int insert(TraineeCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int insertSelective(TraineeCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	List<TraineeCourse> selectByExample(TraineeCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	TraineeCourse selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TraineeCourse record, @Param("example") TraineeCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int updateByExample(@Param("record") TraineeCourse record, @Param("example") TraineeCourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int updateByPrimaryKeySelective(TraineeCourse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_trainee_course
	 * @mbggenerated  Mon Mar 19 17:06:11 CST 2018
	 */
	int updateByPrimaryKey(TraineeCourse record);
}