package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TraineeCourseHomework;
import com.deodio.elearning.persistence.model.TraineeCourseHomeworkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraineeCourseHomeworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int countByExample(TraineeCourseHomeworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int deleteByExample(TraineeCourseHomeworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int insert(TraineeCourseHomework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int insertSelective(TraineeCourseHomework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    List<TraineeCourseHomework> selectByExample(TraineeCourseHomeworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    TraineeCourseHomework selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") TraineeCourseHomework record, @Param("example") TraineeCourseHomeworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int updateByExample(@Param("record") TraineeCourseHomework record, @Param("example") TraineeCourseHomeworkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int updateByPrimaryKeySelective(TraineeCourseHomework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_homework
     *
     * @mbggenerated Fri Nov 02 09:29:04 CST 2018
     */
    int updateByPrimaryKey(TraineeCourseHomework record);
}