package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TraineeAppraise;
import com.deodio.elearning.persistence.model.TraineeAppraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraineeAppraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int countByExample(TraineeAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int deleteByExample(TraineeAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int insert(TraineeAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int insertSelective(TraineeAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    List<TraineeAppraise> selectByExample(TraineeAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    TraineeAppraise selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TraineeAppraise record, @Param("example") TraineeAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int updateByExample(@Param("record") TraineeAppraise record, @Param("example") TraineeAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int updateByPrimaryKeySelective(TraineeAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_appraise
     *
     * @mbggenerated Thu Mar 29 14:29:50 CST 2018
     */
    int updateByPrimaryKey(TraineeAppraise record);
}