package com.deodio.elearning.persistence.mapper;

import com.deodio.elearning.persistence.model.TraineeCourseRecord;
import com.deodio.elearning.persistence.model.TraineeCourseRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TraineeCourseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int countByExample(TraineeCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int deleteByExample(TraineeCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int insert(TraineeCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int insertSelective(TraineeCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    List<TraineeCourseRecord> selectByExample(TraineeCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    TraineeCourseRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") TraineeCourseRecord record, @Param("example") TraineeCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int updateByExample(@Param("record") TraineeCourseRecord record, @Param("example") TraineeCourseRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int updateByPrimaryKeySelective(TraineeCourseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trainee_course_record
     *
     * @mbggenerated Tue Aug 01 15:30:31 CST 2017
     */
    int updateByPrimaryKey(TraineeCourseRecord record);
}